Show concrete instance error
kinvolk/nebraska pull request #269
Opened 2020-08-22 13:15 UTC by ashu8912

2020-08-25 11:31 UTC, pothos commented on pkg/api/instances.go
> +		if instanceStatusHistoryEntity.Status == 3 {
Suggestion: Try to use `InstanceStatusError` instead of `3`

Same for line 282

2020-08-25 11:35 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +
```suggestion
// Keep in sync with https://github.com/flatcar-linux/update_engine/blob/flatcar-master/src/update_engine/action_processor.h#L25
```

2020-08-25 11:48 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +  let flag = Object.keys(flagsCodes).find((flagCode) => (errorCode & flagCode) !== 0);
I think it would be easier to first go through all the flags and detect them, and in a second step calculate errorCodeVal having it cleaned from all flags.

2020-08-25 12:13 UTC, pothos commented
Tested it and so far it worked great, thanks!

2020-08-25 12:18 UTC, pothos commented
Submitting a fake error makes the label empty:

```
$ cat step-1
<?xml version="1.0" encoding="UTF-8"?>
<request protocol="3.0" version="update_engine-0.4.10" updaterversion="update_engine-0.4.10" installsource="scheduler" ismachine="1">
    <os version="Chateau" platform="CoreOS" sp="2512.2.0_x86_64"></os>
    <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" version="1.2.3" track="stable" bootid="{965fb4c5-ad3e-4eb7-a4c2-ca0c0e31ec84}" oem="ami" oemversion="0.1.1-r1" alephversion="1688.5.3" machineid="2b9e671d61774703ac7be60715220bfe" lang="en-US" board="amd64-usr" hardware_class="" delta_okay="false" >
        <updatecheck></updatecheck>
    </app>
</request>
$ cat step-2
<?xml version="1.0" encoding="UTF-8"?>
<request protocol="3.0" version="update_engine-0.4.10" updaterversion="update_engine-0.4.10" installsource="scheduler" ismachine="1">
    <os version="Chateau" platform="CoreOS" sp="2512.2.0_x86_64"></os>
    <app appid="e96281a6-d1af-4bde-9a0a-97b76e56dc57" version="1.2.3" track="stable" bootid="{965fb4c5-ad3e-4eb7-a4c2-ca0c0e31ec84}" oem="ami" oemversion="0.1.1-r1" alephversion="1688.5.3" machineid="2b9e671d61774703ac7be60715220bfe" lang="en-US" board="amd64-usr" hardware_class="" delta_okay="false" >
        <event eventtype="3" eventresult="0" errorcode="999"></event>
    </app>
</request>
$ curl -d @step-1  -H 'Content-Type: text/xml' http://localhost:8000/v1/update
$ curl -d @step-2  -H 'Content-Type: text/xml' http://localhost:8000/v1/update
```

2020-08-25 12:22 UTC, pothos commented
Using `errorcode="267435474"` makes JavaScript go crazy until I kill the tab

2020-08-25 16:27 UTC, ashu8912 commented on pkg/api/instances.go
> +		if instanceStatusHistoryEntity.Status == 3 {
aah nice catch thanks

2020-08-25 16:32 UTC, ashu8912 commented
@pothos how should fake error cases be dealt, I was an assumption that we will always be getting a valid error code

2020-08-25 17:47 UTC, ashu8912 commented
fixed the getErrorsAndFlags function it returns no errors if a wrong error code is passed

2020-08-25 17:54 UTC, ashu8912 commented
now in case of a wrong error_code we fallback to error message saying error updating

2020-08-25 18:03 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +  while (errorCodeVal > 3000){
This can loop endlessly. I'm no JS expert but I would do a for loop here. For each flag, test whether it's set and push it, then clean this flag.

2020-08-25 18:23 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +  }
Maybe add a third case where `errorCodeVal` is turned into a string `Unknown Error 123`

2020-08-25 18:23 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +  }
Then `errorMessage` doesn't need to be a list and the code in `getInstanceStatus` doesn't need to handle an empty list.

2020-08-25 18:28 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +
An additional idea would be to have a nicer error name here like `Response empty` instead of `OmahaRequestEmptyResponseError` etc.

2020-08-25 18:30 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +  }
Displaying the number for unknown errors may help if we add a new error in the future and Nebraska is not yet updated.

2020-08-26 09:02 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +  }
Thanks

2020-08-26 09:07 UTC, pothos approved these changes
Looks good now overall, just need to decide if we want to display `PayloadSizeMismatchError` as is or rename it here to a nicer name like `Payload size did not match` @joaquimrocha

2020-08-26 12:12 UTC, joaquimrocha commented on frontend/src/js/components/Instances/Details.js
> +  console.log(statusObj);
Left over debug print.

2020-08-26 12:12 UTC, joaquimrocha commented on frontend/src/js/components/Instances/Details.js
> +  console.log(statusObj);
Add a newline instead.

2020-08-26 12:18 UTC, joaquimrocha commented on frontend/src/js/components/Instances/Details.js
> +  if (statusObj.label === 'Error'){
Add a space between `)` and `{`.

2020-08-27 10:21 UTC, joaquimrocha requested changes
Almost there. Please check the small comment I left + the changes we talked about on Slack.

2020-08-27 15:04 UTC, joaquimrocha requested changes
Some comments, but it's getting there.

2020-08-27 15:04 UTC, joaquimrocha commented on frontend/src/js/__tests__/Activity/Container.spec.js
> +      </BrowserRouter>
Do you really need to use `BrowserRouter` here? Wouldn't it work without?
If it doesn't work without it, what are the implications of wrapping it around the base app instead of individual components?

2020-08-27 15:27 UTC, ashu8912 commented on frontend/src/js/__tests__/Activity/Container.spec.js
> +      </BrowserRouter>
So while testing or in normal cases as well => a component which uses components from react-router or react-router-dom its mandatory to wrap it in a Parent Router which can be either BrowserRouter or HashRouter

2020-08-27 17:03 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +  '43': 'NewPCRPolicyHTTPError',
I have one more error code added in this (yet unmerged) PR: https://github.com/flatcar-linux/update_engine/pull/6

2020-08-27 17:47 UTC, ashu8912 commented on frontend/src/js/constants/helpers.js
> +  '43': 'NewPCRPolicyHTTPError',
@pothos should i wait for it to merge?

2020-08-27 19:24 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +  '43': 'NewPCRPolicyHTTPError',
No need to wait

2020-08-27 19:50 UTC, ashu8912 commented on frontend/src/js/constants/helpers.js
> +  '43': 'NewPCRPolicyHTTPError',
added

2020-08-27 19:56 UTC, pothos commented on frontend/src/js/constants/helpers.js
> +  '43': 'NewPCRPolicyHTTPError',
ok^^ I meant it's ok to merge without but thanks for adding it, I will keep you posted

2020-08-27 21:12 UTC, joaquimrocha commented
@ashu8912 In the interest of saving time I removed the change of `Error update` -> `Error` because what we needed to do was not touch that label in a patch that's not about that. I kind of mixed things and had understood you had made `Error` -> `Error Update` but you were just capitalizing the word (and either change should not be in this commit).

2020-08-27 21:15 UTC, merged