backend: Make track name to group mapping dynamic
kinvolk/nebraska pull request #284
Opened 2020-10-02 12:24 UTC by pothos

The mapping of Omaha track to a group ID was hardcoded for the stable,
beta, alpha, and edge channel using only the initial the group IDs.
When the groups were recreated resolving the track was broken and new
groups always had to use the group ID as track which was confusing.
Calculate the mapping dynamically based on the channel architecture and
the track name as the slugified group name. Instead of adding yet
another field and either having a complex query using one of the track
name or the ID, or a two queries with the first query resolving a
possible track name and a second query using it or the ID, the
implementation uses a hash map cache which is swapped out when a group
entry needs an update. The slug name should be displayed in the UI
besides the group ID but this is not yet implemented.

2020-10-08 11:21 UTC, joaquimrocha requested changes
Some comments on the code. Let's talk on Slack about the approach.

2020-10-08 11:21 UTC, joaquimrocha commented on pkg/api/groups.go
> +		groups, err := api.GetGroups(flatcarAppID, 0, uint64(maxInt64))
There is `getGroups(appID string)`, shouldn't you use this one instead?

2020-10-08 11:29 UTC, pothos commented on pkg/api/groups.go
> +		groups, err := api.GetGroups(flatcarAppID, 0, uint64(maxInt64))
Ah, yes, this code was moved from a place where `getGroups` was not accessible because it is a private function.

2020-10-08 12:08 UTC, pothos commented on pkg/api/groups.go
> +// There is no guaranetee that it is unique and this has to be taken care of
Removed the code

2020-10-08 12:09 UTC, pothos commented on pkg/api/groups.go
> +	return slugified
Replaced by using the channel name

2020-10-09 11:10 UTC, pothos commented
Will be reworked to have a new database field.

2020-11-04 06:10 UTC, closed without merging