Syncer configuration
kinvolk/nebraska pull request #285
Opened 2020-10-08 11:54 UTC by pothos

- pkg/syncer/syncer: Add parameters for sync interval and source URL
    The interval was hardcoded to one hour which is inconvenient when new
    settings should be quickly propagated during a test phase. The sync
    URL was also hardcoded and required source code changes when a different
    source URL should has to be used.
    Expose both values as parameters with the current values as default.
- pkg/syncer/syncer: Reduce waiting time between two channels
    The syncer was sleeping for a minute before the next channel was
    synced. This makes it look like a bug and even if known it is not
    really useful but rather disturbing to wait 8 minutes until all
    channels are synced.
    Wait for 5 seconds which is a bit waiting time to not hammer the
    server but still allows to sync all channels in under a minute.

2020-10-08 13:38 UTC, joaquimrocha requested changes
Small comment.

2020-10-08 13:38 UTC, joaquimrocha commented on cmd/nebraska/nebraska.go
> +	checkFrequencyVal   = flag.String("sync-interval", "1h", fmt.Sprintf("Sync check interval (the minimum depends on the number of channels to sync, e.g., 8m for 8 channels incl. different architecture
I realize other lines are using the `Sprintf` function here, but that was probably a mistake and they can/should be plain strings, right?

2020-10-08 13:38 UTC, joaquimrocha commented on cmd/nebraska/controller.go
> +	checkFrequency      time.Duration
Nitpick: The sync interval and source URL are independent, so this should be slipt into two commits.

2020-10-12 02:23 UTC, pothos commented on cmd/nebraska/controller.go
> +	checkFrequency      time.Duration
Semantically yes, but due to the reformatting they wouldn't be independent from each other anyway and the first can't be reverted without conflicts.

2020-10-12 02:23 UTC, pothos commented on cmd/nebraska/nebraska.go
> +	checkFrequencyVal   = flag.String("sync-interval", "1h", fmt.Sprintf("Sync check interval (the minimum depends on the number of channels to sync, e.g., 8m for 8 channels incl. different architecture
Good catch, updated

2020-10-12 13:27 UTC, joaquimrocha approved these changes

2020-10-12 13:28 UTC, merged