README: Add CoC and commit guidelines
kinvolk/nebraska pull request #288
Opened 2020-10-23 10:50 UTC by joaquimrocha

Kinvolk now has a Contribution repository with a Code of Conduct as well
as PR/commit guidelines, so we mention them in the README.

2020-10-23 15:52 UTC, vbatts requested changes

2020-10-23 15:52 UTC, vbatts commented on README.md
> +[contribution guidelines on git](https://github.com/kinvolk/contribution/tree/master/git).
same https://github.com/kinvolk/dev-utils/pull/6#discussion_r510979794

2020-10-28 12:01 UTC, joaquimrocha commented
Updated.

2020-10-28 18:45 UTC, vbatts commented
LGTM

2020-10-28 18:45 UTC, merged