Optimize update instance status
kinvolk/nebraska pull request #289
Opened 2020-10-23 20:37 UTC by joaquimrocha

Some small optimizations but that happen in the crucial during `getUpdatePackage`.

2020-10-26 13:42 UTC, vbatts commented on pkg/api/instances.go
> +		FromQuery(goqu.From(goqu.L(helperTableName)).
i wonder if some of these intermediary queries could get cached, with a TTL of like 30sec.
Many times, each host pinging is only interested in its own row, so if the sheet was only fresh within 30sec, and there had been other updates in that time, it would not have affected its own row.
This cache would save the bombardment of queries, if multiple callers could reuse the same cache.

2020-10-28 10:21 UTC, joaquimrocha commented on pkg/api/instances.go
> +		FromQuery(goqu.From(goqu.L(helperTableName)).
Sure. Caching and queueing is a good strategy that it's in our plans, but we need to understand exactly what it means if we use the stored data for deciding on the policy, i.e. if you have "update only 200 instances every 15 minutes" and you use a 30-second valid cache for the data but you receive 1000 requests in 15 seconds, we cannot block them beyond 200 instances.

This is an example of why I want to take a step at a time. For other stuff not implied in the policy enforcing, for sure we could cache them.

2020-11-06 17:35 UTC, krnowak requested changes
Looks mostly good. Had some nitpicks and questions.

2020-11-06 17:35 UTC, krnowak commented on pkg/api/instances.go
> +func (api *API) updateInstanceData(instance *Instance, data *map[string]interface{}) error {
There is no need to make `data` a pointer to map. Map types are pointer-like themselves, so passing them "by value" is cheap. So:
```suggestion
func (api *API) updateInstanceData(instance *Instance, data map[string]interface{}) error {
```

2020-11-06 17:35 UTC, krnowak commented on pkg/api/instances.go
>  		Cols("status", "version", "instance_id", "application_id", "group_id").
You could see https://pkg.go.dev/github.com/doug-martin/goqu/v9@v9.9.0#InsertDataset.With for the `WITH` support.

I suppose that it would look something like this:
```go
// we are not calling ToSQL() for updateQuery here!
updateQuery := goqu.Update("instance_application").YaddaYadda().Returning(…)
insertQuery, _, err := goqu.Insert("instance_status_history").
	With(helperTableName, updateQuery).
	FromQuery(…).
	Select(…).
ToSQL()
```

2020-11-06 17:35 UTC, krnowak commented on pkg/api/updates.go
> +	MaxParallelUpdates = 900000
Where does this number come from?

2020-11-06 17:35 UTC, krnowak commented on pkg/api/updates.go
> +	MaxParallelUpdates = 900000
And does it need to be exported? (Starts with an upper case.)

2020-11-06 17:35 UTC, krnowak commented on pkg/api/updates.go
> +	if !api.hasRecentActivity(activityRolloutStarted, ActivityQueryParams{Severity: activityInfo, AppID: appID, Version: version, GroupID: group.ID}) {
I can assume that this is a cheaper equivalent of getting `updatesStats.UpdatesToCurrentVersionGranted`, right?

2020-11-11 03:30 UTC, pothos commented on pkg/api/instances.go
> +	// transation below.
```suggestion
	// transaction below.
```

2020-11-11 12:46 UTC, joaquimrocha commented on pkg/api/instances.go
>  		Cols("status", "version", "instance_id", "application_id", "group_id").
I did test some combinations of `With` before and couldn't make it work with `Insert` but I guess I was not applying it correct because your suggestion works! Thanks!

2020-11-11 12:48 UTC, joaquimrocha commented on pkg/api/instances.go
> +		// Skip updating anything unnecessary
I don't think mine is incorrect. There were unnecessary things being updated. So we skip things that are unnecessary :slightly_smiling_face:

2020-11-11 12:51 UTC, joaquimrocha commented on pkg/api/instances.go
> +func (api *API) updateInstanceData(instance *Instance, data *map[string]interface{}) error {
This change gets me nervous, but you're coming from C++ too, so I will accept it.

2020-11-11 12:54 UTC, joaquimrocha commented on pkg/api/activity.go
> +	recent := time.Now().UTC().Add(time.Duration(-24*60) * time.Minute)
Thanks!

2020-11-11 12:59 UTC, joaquimrocha commented on pkg/api/updates.go
> +	if !api.hasRecentActivity(activityRolloutStarted, ActivityQueryParams{Severity: activityInfo, AppID: appID, Version: version, GroupID: group.ID}) {
It's not cheap against checking a boolean in memory, but it's cheap in most of the cases, especially when one is not limiting the updates, because we don't need to fetch the whole stats for the group (as it's a complex query).

2020-11-11 13:02 UTC, joaquimrocha commented on pkg/api/updates.go
> +	MaxParallelUpdates = 900000
It's just an insanely huge number for checking updates in parallel, so instead of having a boolean check for whether we care for updates, I am using this number. We will limit to this number in the UI soon too.

2020-11-11 13:09 UTC, joaquimrocha commented
PR updated. Thanks for the reviews.

2020-11-11 13:53 UTC, krnowak approved these changes
One typo, otherwise looks good.

2020-11-11 13:53 UTC, krnowak commented on pkg/api/instances.go
> +	// We want to avoid having to create an unneeded DB transation, so we check whether it
```suggestion
	// We want to avoid having to create an unneeded DB transaction, so we check whether it
```

2020-11-11 13:53 UTC, krnowak commented on pkg/api/instances.go
> +		// Skip updating anything unnecessary
Yep, you are right. Let's leave it as is then.

2020-11-11 14:05 UTC, krnowak commented on pkg/api/instances.go
> +func (api *API) updateInstanceData(instance *Instance, data *map[string]interface{}) error {
Oh yeah, from that angle I can understand why it makes you nervous. Coming from that background, maps can have a bit weird semantics, see https://play.golang.org/p/RMG9kLd4d2L.

2020-11-11 16:09 UTC, joaquimrocha commented on pkg/api/instances.go
> +	// We want to avoid having to create an unneeded DB transation, so we check whether it
Fixed. Thanks.

2020-11-11 16:13 UTC, merged