WIP: Port frontend codebase to typescript
kinvolk/nebraska pull request #325
Opened 2021-01-25 14:38 UTC by ashu8912

2021-01-25 16:57 UTC, illume reviewed
Massive work :)

I left some comments in a first pass review. I haven't tried to run it yet, or test it in other ways yet.

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Applications/ApplicationItemGroupsList.react.tsx
> +import { Box, Divider } from '@material-ui/core';
Seems that git didn't pick up the rename here for some reason.
frontend/src/js/components/Applications/ApplicationItemGroupsList.react.js -> frontend/src/js/components/Applications/ApplicationItemGroupsList.react.tsx

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Applications/EditDialog.tsx
> +        //@ts-ignore
Why is this ignored?

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Applications/Item.react.tsx
> -  const channels = props.application.channels || [];
Was this supposed to be used for something?

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Applications/List.react.tsx
> +import {List as MuiList, withStyles} from '@material-ui/core';
The rename wasn't detected by git for some reason. frontend/src/js/components/Applications/List.react.js -> frontend/src/js/components/Applications/List.react.tsx

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Channels/EditDialog.tsx
> +  //@ts-ignore
Why is this ignored?

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Channels/EditDialog.tsx
> +  function handleSubmit(values: {[key: string]: any}, actions: {[key:string]: any}) {
Not sure about having `any` here for actions and values. Is adding more specific types possible?

2021-01-25 16:57 UTC, illume commented on frontend/src/js/stores/GroupChartsStore.ts
> +  setVersionChartData(groupID: string, duration: string, data: any) {
Should data have a more specific type?

2021-01-25 16:57 UTC, illume commented on frontend/src/js/stores/BaseStore.ts
> +  addChangeListener(callback: () => any) {
Should any be used here?

2021-01-25 16:57 UTC, illume commented on frontend/src/js/stores/ApplicationsStore.ts
> +  createApplication(data: any, clonedApplication: string) {
Can a more specific type be used here than any?

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Main.react.tsx
> +declare module '@material-ui/core/styles/createPalette' {
I don't understand this.

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Instances/Table.tsx
> +          [key: string]: any
More specific type here than any possible?

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Instances/StatusHistoryContainer.react.tsx
> +  let entries: string | React.ReactElement = '';
Instead of the empty string, this could be an assignment using a ternary operator.

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Instances/List.tsx
> +    const pageQueryParam = (parseInt(queryParams.get('page') as string) || 1) - 1;
URLSearchParams.get can return string | null (if the param is not there).

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Instances/Item.react.js
>  import Link from '@material-ui/core/Link';
Looks like this has not been converted to a tsx yet.

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Groups/EditDialog.tsx
> +        //@ts-ignore
Why is this ignored?

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Common/TimezonePicker.tsx
> +                    //@ts-ignore
Why is this ignored?

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Common/MoreMenu.tsx
> +export default function MoreMenu(props: {options: any[]}) {
options may need a type

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Common/ListSearch.tsx
> +export default function SearchInput(props: object) {
The type here could be improved.

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Common/ConfirmationContent.react.tsx
> +import PropTypes from 'prop-types';
The git rename didn't work here.

2021-01-25 16:57 UTC, illume commented on frontend/src/js/components/Common/AutoCompletePicker.tsx
> +                    options={getSuggestions(inputValue as string, selectedItem, suggestions)}
not sure about the type of inputValue here, and if the other types need to be handled differently.

2021-01-29 17:26 UTC, ashu8912 commented on frontend/src/js/components/Activity/Container.react.tsx
> +  function handleChangePage(event: React.MouseEvent<HTMLButtonElement, MouseEvent> | null, newPage: number) {
I took this type definition from TablePagination(which is a part of material-ui) where this handleChangePage is used and there the type for event was this

2021-01-29 17:26 UTC, ashu8912 commented on frontend/src/js/components/Activity/Item.react.tsx
> -const useStyles = makeStyles(theme => ({
Yeah it was an unused code

2021-01-29 18:11 UTC, ashu8912 commented on frontend/src/js/components/Applications/Item.react.tsx
> -  const channels = props.application.channels || [];
it was an unused variable

2021-01-29 18:14 UTC, ashu8912 commented on frontend/src/js/components/Channels/EditDialog.tsx
> +  function handleSubmit(values: {[key: string]: any}, actions: {[key:string]: any}) {
handleSubmit is passed to formik and it has defined this function signature as this

2021-01-29 18:29 UTC, ashu8912 commented on frontend/src/js/components/Main.react.tsx
> +declare module '@material-ui/core/styles/createPalette' {
The useTheme() hook we use doesn't know much about the types of custom added theme properties this is a declaration for the palette so that useTheme knows out custom set properties as well

2021-01-29 19:28 UTC, ashu8912 commented on frontend/src/js/components/Common/TimezonePicker.tsx
> +                    //@ts-ignore
I have ignored this for now as setting up types for formik functions is a bit complex but will sure give them a revisit

2021-02-01 16:14 UTC, illume commented on frontend/src/js/components/Common/TimezonePicker.tsx
> +                    //@ts-ignore
Cool. I guess put a @todo here?

2021-02-01 16:19 UTC, illume commented on frontend/src/js/components/Applications/EditDialog.tsx
> +        //@ts-ignore
We could put a `@todo` here.

2021-02-01 16:25 UTC, illume commented on frontend/src/js/stores/GroupChartsStore.ts
> +  setStatusChartData(groupID: string, duration: string, data: any) {
I guess `data: any` here could be like the other one and be `data: {[key: string]: string;}`.

2021-02-01 16:27 UTC, illume commented on frontend/src/js/stores/ApplicationsStore.ts
> +  createGroup(data: any) {
Probably the same data type as what createApplication uses. Also for other methods that use data in this component.

2021-02-01 16:46 UTC, illume commented on frontend/src/js/components/Applications/Item.react.tsx
> -  const channels = props.application.channels || [];
Should channels be displayed in this component?

2021-02-01 16:49 UTC, illume commented on frontend/src/js/components/Activity/List.react.tsx
> +        {entries.map((entry: Activity, i: number) =>
I'll resolve this conversation, and make a note for checking all the keys later.

2021-02-01 17:04 UTC, illume commented on frontend/src/js/components/Main.react.tsx
> +      main: process.env.REACT_APP_PRIMARY_COLOR as string,
How about this to avoid the type cast?
`main: REACT_APP_PRIMARY_COLOR ? REACT_APP_PRIMARY_COLOR : '#2C98F0',`

2021-02-01 17:14 UTC, illume commented on frontend/src/js/components/Main.react.tsx
> +declare module '@material-ui/core/styles/createPalette' {
Ok, thanks.

2021-02-01 17:16 UTC, illume commented on frontend/src/js/components/Main.react.tsx
> +declare module '@material-ui/core/styles/createPalette' {
I did see it's possible to override the types something like this below, but it adds a bunch of verbosity. I think your way is better.

```ts
declare module '@material-ui/core/styles/createMuiTheme' {
  interface Theme {
    palette: {
      titleColor: string;
      lightSilverShade: string;
      greyShadeColor: string;
      sapphireColor: string;
    };
  }
  // allow configuration using `createMuiTheme`
  interface ThemeOptions {
    palette?: {
      titleColor?: string;
      lightSilverShade?: string;
      greyShadeColor?: string;
      sapphireColor?: string;
    };
  }
}
```

2021-02-01 17:21 UTC, illume commented
There's a few cases where git is not picking up renames.

Probably the ".react.tsx" names could just be ".tsx".

Is there a plan for testing this?

2021-02-16 00:47 UTC, illume commented on frontend/src/js/components/Activity/Item.tsx
> +import alertCircleOutline from '@iconify/icons-mdi/alert-circle-outline';
Looks like the git rename isn't working for this file.

2021-02-16 00:51 UTC, illume commented on frontend/src/js/components/Applications/ApplicationItemChannelsList.react.tsx
>  import Grid from '@material-ui/core/Grid';
I don't think the react in the name is necessary, it can just be `ApplicationItemChannelsList.tsx`

2021-02-16 00:51 UTC, illume commented on frontend/src/js/components/Applications/ApplicationItemGroupsList.tsx
> +import { Box, Divider } from '@material-ui/core';
This one didn't git rename properly.

2021-02-16 00:55 UTC, illume commented on frontend/src/js/components/Groups/List.react.tsx
> +import { withStyles } from '@material-ui/core';
Git rename didn't work in this one. It probably doesn't need a ".react" in the name.

2021-02-16 00:56 UTC, illume commented on frontend/src/js/components/Instances/Common.tsx
> +    color: (theme as Theme).palette.greyShadeColor
I think the type could be moved up to the function definition?
`const useInstanceCountStyles = makeStyles(theme: Theme => ({`

2021-02-16 00:58 UTC, illume commented on frontend/src/js/components/Instances/Details.js
> +  onInstanceUpdated: PropTypes.func
I guess the propTypes could be moved up into TypeScript.

2021-02-16 01:05 UTC, illume commented on frontend/src/js/components/Instances/StatusHistoryItem.react.tsx
> +import { Box } from '@material-ui/core';
The git rename didn't work on this one.

2021-02-16 01:11 UTC, illume commented
Hey hey. I looked through this again, and resolved a number of comments and left a few more. I think fixing the git rename issues are important so that the history still works.

If there's any thing you want me to check, or test in particular let me know :)

2021-02-16 17:19 UTC, ashu8912 commented on frontend/src/js/components/Applications/ApplicationItemChannelsList.react.tsx
>  import Grid from '@material-ui/core/Grid';
fixed the name

2021-02-16 17:20 UTC, ashu8912 commented on frontend/src/js/components/Instances/Common.tsx
> +    color: (theme as Theme).palette.greyShadeColor
thanks, done.

2021-02-16 17:21 UTC, ashu8912 commented on frontend/src/js/components/Instances/Details.js
> +  onInstanceUpdated: PropTypes.func
it's still a js file and is yet not ported some files in the instances directory are still to be ported and this is among them, I have kept some of these for a later pr because there is a issue regarding importing images in ts that i still need to figure out.

2021-02-18 17:46 UTC, illume commented on frontend/src/js/components/Applications/List.tsx
> +import {List as MuiList, withStyles} from '@material-ui/core';
git rename confused again.

2021-02-18 17:50 UTC, illume commented on frontend/src/js/components/Channels/EditDialog.tsx
> +  function handleSubmit(values: {[key: string]: any}, actions: {[key:string]: any}) {
Makes sense, thanks.

2021-02-18 17:56 UTC, illume commented on frontend/src/js/components/Channels/EditDialog.tsx
> +      arch: arch,
I'm unsure if this doesn't need to use the parseInt anymore?

2021-02-18 17:59 UTC, illume commented on frontend/src/js/components/Common/ConfirmationContent.tsx
> +import React from 'react';
git rename is confused again

2021-02-18 18:06 UTC, illume commented on frontend/src/js/components/Instances/List.tsx
>      const duration = queryParams.get('period');
duration may not always be a string.

2021-02-18 18:11 UTC, illume commented
A general note, the "`theme as Theme`" cast can be replaced by by typing theme in the function params. Probably it's easier to search and replace them all at once, than for me to point out each one separately.

2021-02-18 18:17 UTC, illume commented on frontend/src/js/stores/ApplicationsStore.ts
> +    return _.findWhere(this.applications as Collection<any>, {id: applicationID});
(Off topic, but I guess findWhere can mostly be replaced by find these days. Untested, so don't use... `this.applications.find(a => a.id === applicationID)`)

2021-02-18 18:22 UTC, illume commented on frontend/src/js/components/Instances/StatusHistoryContainer.tsx
> +  let entries: string | React.ReactElement = '';
The string assignment can be replaced by assigning entries directly.

2021-02-18 18:23 UTC, illume commented on frontend/src/js/components/Instances/StatusHistoryItem.tsx
> +import { Box } from '@material-ui/core';
A git rename confusion.

2021-02-18 18:26 UTC, illume commented on frontend/src/js/components/Layouts/ApplicationLayout.tsx
> +import Grid from '@material-ui/core/Grid';
gitty gitty rename

2021-02-18 18:29 UTC, illume commented on frontend/src/js/components/Layouts/InstanceLayout.tsx
> +  function getGroupFromApplication(app: Application | undefined) {
If the return value is typed, then some other casts might not need to be used.

2021-02-18 18:30 UTC, illume commented on frontend/src/js/components/Layouts/InstanceLayout.tsx
> +        group={group as Group}
See note about getGroupFromApplication

2021-02-18 18:38 UTC, illume commented on frontend/src/js/constants/helpers.ts
> +  .filter((interval) => interval.queryValue === '1d')[0];
I don't understand why this was changed to filter if only the first element is used?

2021-02-18 18:38 UTC, illume commented on frontend/src/js/constants/helpers.ts
> +      //@ts-ignore
What is the reason for this ts-ignore?

2021-02-18 18:41 UTC, illume commented on frontend/src/js/components/Layouts/GroupLayout.tsx
> +import React from 'react';
A git rename issue.

2021-02-18 18:42 UTC, illume commented on frontend/src/js/components/Groups/List.tsx
> +import { withStyles } from '@material-ui/core';
A git rename issue.

2021-02-19 09:37 UTC, ashu8912 commented on frontend/src/js/components/Channels/EditDialog.tsx
> +      arch: arch,
No arch is obtained from backend and is present on Channel interface and its type is number it was an unnecessary parseInt that we had in place

2021-02-19 09:56 UTC, ashu8912 commented on frontend/src/js/components/Common/ConfirmationContent.tsx
> +import React from 'react';
How? I added a rename commit before this commit because git was not letting me commit a file with lot of changes as a rename commit

2021-02-19 10:31 UTC, ashu8912 commented on frontend/src/js/components/Instances/List.tsx
>      const duration = queryParams.get('period');
yes but we are safe here because even if we pass null in the api the backend will handle it

2021-02-22 23:10 UTC, illume commented
Weird... the github files tab still isn't updating correctly it seems. I see the rename works with ChannelAvatar.tsx with git cmd but not online when reviewing. (It makes reviewing the files through the web harder).
```
git log --follow frontend/src/js/components/Channels/ChannelAvatar.tsx
```
I also see the move in the commit online... https://github.com/kinvolk/nebraska/pull/325/commits/36c2a553e34bf2fcac2262847f8c47b28d284395

But then when I do this locally...

2021-02-23 15:31 UTC, illume commented
@joaquimrocha we can't seem to figure out why some files are not renaming properly in the github interface. The commits had the dates fixed up to be chronological, we tried opening a new PR just incase that would help (it didn't). One example is the ChannelAvatar.tsx file, which looks fine from the command line, but not in the github webview. It seems odd, but we've ran out of ideas... if no one can spot anything wrong... then I perhaps we are ok to merge with the files github doesn't show as renamed in the web view.

I'm going to review those remaining rename-troubled files from the command line. 

For the curious, commands like this seem to work best for reviewing renamed files (where `HEAD~100` in this command is the pre-typescript commit).
```
# git diff HEAD~100:old-file new-file
git diff HEAD~100:frontend/src/js/components/Channels/ChannelAvatar.js frontend/src/js/components/Channels/ChannelAvatar.tsx
```

2021-02-24 12:03 UTC, joaquimrocha requested changes
Left just a couple of comments, and on Slack as well about some of the comments René had left (which I think should be addressed, or replied to at least).

2021-02-24 12:03 UTC, joaquimrocha commented on frontend/src/js/components/Packages/EditDialog.tsx
> +      arch: arch,
We had some issues before because of the arch being set as a string instead of a number. So this change may be problematic.

2021-02-24 12:03 UTC, joaquimrocha commented on frontend/src/js/components/Packages/EditDialog.tsx
> +    const data: any = {
Even if it requires some labor, I think it's better we type this.

2021-02-25 11:54 UTC, ashu8912 commented on frontend/src/js/constants/helpers.ts
> +  .filter((interval) => interval.queryValue === '1d')[0];
Ooh so find returns whether the value | undefined(in case the value is not there) but `timeIntervalsDefault ` is a const object which has a '1d' queryValue objcet in it so changing to filter prevents us handling the undefined case because we know for sure that there is a '1d' value in the `timeIntervalsDefault` Object

2021-02-25 11:54 UTC, ashu8912 commented on frontend/src/js/constants/helpers.ts
> +      //@ts-ignore
The reason for the ts-ignore here is type indexing type Color was throwing an error so something like 
lime(of type color)[300] is not allowed, 
This is amongst some of the ignores that i need to revisit

2021-02-26 10:03 UTC, joaquimrocha commented
@ashu8912 , the code looks overall fine to me. However, I tried this branch on staging and noticed that when creating a new group, the group is not shown on the UI until I refresh the page. This didn't happen on 2.3.1, so maybe you can check whether it's a regression from your changes.

2021-02-26 14:56 UTC, ashu8912 commented
@joaquimrocha i have fixed the adding group | app bug

2021-02-26 15:33 UTC, merged