Draft: Initial helm chart
kinvolk/nebraska pull request #330
Opened 2021-02-02 10:52 UTC by mkilchhofer

# Deploy via helm chart

I use nebraska in my homelab to update my flatcar hosts esp. to reduce the traffic for downloading the new images.
For this I am working on a helm chart. The chart is in WIP state.
Are you interested in this? I found not that much information about deploying and hosting nebraska in production.

What also could be nice to provide:
- docs about deploying in Kubernetes (with example yamls)
- Deploy with Kustomize
- GitHub Actions for hosting the chart as a static resource in gh-pages

# How to use

TODO: [ describe what reviewers need to do in order to validate this PR ]

# Testing done

TODO: [Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]

2021-02-08 11:44 UTC, joaquimrocha commented
@johananl , Do you wanna take a look at this one?

2021-02-25 02:33 UTC, knrt10 requested changes
@mkilchhofer thank you for opening the PR. Really great work. Some NITs, can you please address them?

2021-02-25 02:33 UTC, knrt10 commented on deploy/helm/templates/secrets.yaml
>  {{- $user := .Values.postgresql.postgresqlUsername }}
Can you please add commit message why this change is needed?

2021-02-25 02:33 UTC, knrt10 commented on deploy/helm/templates/deployment.yaml
>                value: "{{ .Values.config.auth.github.enterpriseURL }}"
Can you please add a commit message why this change is needed?

2021-02-25 02:33 UTC, knrt10 commented on deploy/helm/Chart.yaml
>  name: nebraska
This commit can be added as a part of the "Initial Helm chart"

2021-02-25 02:33 UTC, knrt10 commented on deploy/helm/Chart.yaml
> +appVersion: "2.3.0"
This can be updated to latest `2.3.2`

2021-02-25 02:33 UTC, knrt10 commented on deploy/helm/Chart.yaml
> +  version: 10.2.6
We can use `10.3.6`, I guess

2021-02-25 07:46 UTC, mkilchhofer commented on deploy/helm/Chart.yaml
>  name: nebraska
My intention was that all these commits gets squash-merged into 1 commit once the PR is accepted. Is that not the case?

2021-02-25 07:46 UTC, mkilchhofer commented on deploy/helm/templates/deployment.yaml
>                value: "{{ .Values.config.auth.github.enterpriseURL }}"
See comment https://github.com/kinvolk/nebraska/pull/330#discussion_r582609015

2021-02-25 07:47 UTC, mkilchhofer commented on deploy/helm/templates/secrets.yaml
>  {{- $user := .Values.postgresql.postgresqlUsername }}
See comment https://github.com/kinvolk/nebraska/pull/330#discussion_r582609015

2021-02-28 20:35 UTC, mkilchhofer commented
Hi @knrt10,
Do you plan to use the branch `gh-pages` and GitHub Pages? If not, I can also add a github action workflow which releases the chart through a GitHub release and updating an index.yaml file inside the branch `gh-pages`.

2021-03-01 10:09 UTC, joaquimrocha commented
Hi @mkilchhofer , we have our own documentation system, so we don't plan on using gh-pages (unless I misunderstood your point).
A Github action to update stuff on release sounds fine. I intend to do that for the container image as well in the future.

2021-03-01 10:23 UTC, joaquimrocha commented
the docs, BTW: https://kinvolk.io/docs/nebraska/latest

2021-03-01 15:30 UTC, mkilchhofer commented
> Hi @mkilchhofer , we have our own documentation system, so we don't plan on using gh-pages (unless I misunderstood your point).
> A Github action to update stuff on release sounds fine. I intend to do that for the container image as well in the future.

Okay, perfect 👌 
We need an empty `gh-pages` branch for this, which I cannot provision inside this PR:
```console
$ # Prepare an empty branch
$ git checkout --orphan gh-pages
$ git reset
$ rm -r *

$ # Generate the index structure
$ cat <<EOF > index.yaml
apiVersion: v1
entries: {}
generated: "2021-03-01T00:00:00Z"
serverInfo: {}
EOF

$ # Add the file
$ git add index.yaml
$ git commit -m 'Add empty index.yaml'
$ git push
```

2021-03-01 20:10 UTC, mkilchhofer commented on .github/workflows/helm-chart-release.yml
> +      - feature/helm-chart
Before merge, we need to change this to `master` only

2021-03-05 14:15 UTC, joaquimrocha commented
Thanks again for another big push @mkilchhofer !
I was going to take a look now too but I'd like to ask you to squash the commits that you think should go together.
Ideally we should have atomic commits. Depending on this case, it may mean that all your commits should be squashed, or maybe there are a few that should be added separately.
However, we usually never squash commits together (unless their small fixups to one base commit) when merging PRs. So I kindly ask you to squash the commits to create the atomic ones you see as adequate, and that'll make the PR easier for another review round and testing.

2021-03-05 14:27 UTC, mkilchhofer commented
Alright, I think split all in 2 commits, 1 for the chart itself and one for the CI part. When you are okay with that :)

2021-03-09 12:35 UTC, knrt10 requested changes
Looks great @mkilchhofer. Some last Nits. Also I tested it, it works fine. Made some changes to description for user as a first time install. Hope that's okay.

2021-03-09 13:35 UTC, knrt10 commented on charts/nebraska/README.md
> +$ helm install my-nebraska nebraska/nebraska
Sounds fine. Reason, if you run it in default Namespace
`Error: container has runAsNonRoot and image will run as root (pod: "my-nebraska-dd97796db-ngdbn_default(4b71e2d7-7e2d-47df-9f97-6124e9849dc6)", container: nebraska)`

Not in the context of this PR, but we can use RBAC for Service account to avoid extra access other than what's needed

2021-03-09 14:01 UTC, knrt10 commented on charts/nebraska/README.md
> +$ helm install my-nebraska nebraska/nebraska
Sounds great.

2021-03-09 14:07 UTC, mkilchhofer commented on charts/nebraska/README.md
> +$ helm install my-nebraska nebraska/nebraska
Maybe we can set these values as defaults. I was not sure, if this is supported yet as I didn't find this inside the docs.
But we can also set it as defaults in a further release, up to you.

2021-03-10 04:59 UTC, knrt10 approved these changes
Thanks for the awesome work @mkilchhofer. LGTM. Tested it again with the new changes. Works fine.

2021-03-16 15:10 UTC, merged

2021-03-16 15:57 UTC, joaquimrocha commented
> Hi @knrt10,
> Do you plan to use the branch `gh-pages` and GitHub Pages? If not, I can also add a github action workflow which releases the chart through a GitHub release and updating an index.yaml file inside the branch `gh-pages`.

Hi @mkilchhofer , I merged the PR but didn't realize it was still trying to use the gh-pages branch (which we don't use).
Can we use an alternative for this? Maybe using the Github Releases as you hinted in the message above, or does that still require the gh-pages branch?

Thanks.

2021-03-16 16:02 UTC, mkilchhofer commented
> > Hi @knrt10,
> > Do you plan to use the branch `gh-pages` and GitHub Pages? If not, I can also add a github action workflow which releases the chart through a GitHub release and updating an index.yaml file inside the branch `gh-pages`.
> 
> Hi @mkilchhofer , I merged the PR but didn't realize it was still trying to use the gh-pages branch (which we don't use).
> Can we use an alternative for this? Maybe using the Github Releases as you hinted in the message above, or does that still require the gh-pages branch?
> 
> Thanks.

Hi @joaquimrocha, Maybe I didn't understand your statement correctly. What I understand was that you do not use the branch `gh-pages` so it is available for this intent :-)

2021-03-16 16:07 UTC, joaquimrocha commented
No :)
I meant I'd prefer to keep not using that branch, but I am guessing there's no greater alternative if we don't intend to host it somewhere else?

2021-03-16 16:14 UTC, mkilchhofer commented
Exactly. We need to serve an `index.yaml` via https to the helm users. A next step could be to list this chart on https://artifacthub.io/ then we would need an additional file for this besides the `index.yaml`