Update/Replace go packages
kinvolk/nebraska pull request #333
Opened 2021-02-15 12:13 UTC by ashu8912

fixes #97

2021-02-15 14:14 UTC, krnowak requested changes
Oh man, logger library change is painful. Thanks for handling it.

So I haven't gone through every single change here, as there are many. But one thing sticks out - our logging is a mess. Both old `logxi` and new `zerolog` are structured loggers, but `logxi` was rather weak at enforcing it, while `zerolog` is more stringent in this regard. So with `logxi` the usual way of passing parameter to logger was `logger.Debug(message, key1, value1, key2, value2, …)`, and we seem to often abuse it in way like `logger.Error("stuff failed", err)`, where err becomes `key1`. With `zerolog`, the way of logging looks more like `logger.Error().Str(key1, value1).Str(key2, value2).Msg(message)`. Or `logger.Error().Err(err).Msg("stuff failed")`. The problem I see here is that in this PR we put all the key-value pairs into the message by turning `logger.Debug("message", key1, value1, key2, value2, …)` into `logger.Debug().Msgf("message %s %s %s %s …", key1, value1, key2, value2, …)`. I'd prefer to keep the key-value and message separation.

So to summarize:
- Please use `Err` for passing errors (which you mostly already do). Not sure if `AnErr` comes in handy anywhere.
- Please use `Str` (or some other type-safe function from https://pkg.go.dev/github.com/rs/zerolog#Event) for key-value pairs.
- Please come up with some guideline for messages (the `Msg` or `Msgf` part). My proposal would be that they are written like "operation - message", so for example "fetching manifest - something bad happened" or "login cb - invalid oauth state".
- The loggers were named (`logger = log.New("auth")`), I suppose this can be useful to preserve (like with `zerolog.New(zerolog.ConsoleWriter{…}).With().Str("context", "auth")`).
- Please fix some of the logging mess/abuse we have.

Some examples:

`logger.Debug("auth metrics", "malformed authorization header", authHeader)` could become `logger.Debug().Str("header", authHeader").Msg("auth metrics - malformed authorization header")`

`logger.Error("login cb", "expected to have a valid desiredurl item in session data")` could become `logger.Error().Msg("login cb - expected to have a valid desiredurl item in session data")`

`logger.Error("addApp - cloning app", "error", err.Error(), "app", app, "sourceAppID", sourceAppID)` could become `logger.Error().Err(err).Str("app", app).Str("sourceAppID", sourceAppID).Msg("addApp - cloning app failed")`

2021-02-17 13:19 UTC, joaquimrocha requested changes
As Krzesimir had noticed, there's a debug script that has been mistakenly added to the PR.
The choice of Zerolog means changing the logging calls in a lot of places. I am curious to know why it was used over Logrus (it's in no-new-features mode but seems to be actively maintained, and is compatible with the log Go API).

2021-02-17 13:19 UTC, joaquimrocha commented on update_nebraska_db_ts.sh
> +#!/bin/env bash
This was probably mistakenly added.

2021-02-23 08:07 UTC, krnowak reviewed
I think there is one more thing to do, which is to set the default logging level to "info", and then either add a `debug` flag or some environment variable to set the logging to the "debug" level.

2021-02-24 10:58 UTC, joaquimrocha approved these changes

2021-02-24 10:59 UTC, merged