oidc wip
kinvolk/nebraska pull request #372
Opened 2021-05-10 17:43 UTC by yolossn

2021-05-27 11:00 UTC, illume commented on frontend/src/js/stores/ApplicationsStore.ts
> +          case 401:
Are these the only status codes that need to be handled?

2021-05-27 11:05 UTC, illume commented on frontend/package.json
> +    "react-redux": "^7.2.4",
For the last 1.5 years or so the way to do idiomatic redux is different to what has been done here. The new way is a significant improvement for readability and reduces errors. IMHO, I think it's worth doing since this is the first time redux is being used in this codebase.

From the redux getting started guide: https://redux.js.org/introduction/getting-started
> Redux Toolkit is our official recommended approach for writing Redux logic.

2021-05-27 11:16 UTC, illume commented on frontend/src/js/__tests__/Applications/__snapshots__/Item.spec.js.snap
> +          class="MuiGrid-root makeStyles-gridHeader-4 MuiGrid-container MuiGrid-justify-xs-space-between"
Seems like the only change here is the auto-generated classname IDs.

There's a generateClassName attribute that allows these IDs to be stable under test used in the Headlamp codebase here: https://github.com/kinvolk/headlamp/pull/202/files#diff-cc96163d7afd1ab1ae4d95870e5479069434913a583bf87706b2c429c56dacaaR22

2021-05-27 11:21 UTC, illume commented on frontend/src/js/components/Footer.tsx
> +  const {title='', nebraska_version=''} = useTypedSelector(state => state.config);
Seems like these defaults would be better set inside the selector?

2021-05-27 11:31 UTC, illume commented on backend/cmd/nebraska/auth/oidcauth.go
> +	loginRedirectURL := c.Request.URL.Query().Get("login_redirect_url")
What if login_redirect_url is not there?

Does the URL need to be validated here?

2021-05-27 11:40 UTC, illume commented on backend/cmd/nebraska/nebraska.go
> +	oidcAdminRoles      = flag.String("oidc-admin-roles", "", "comma-separated list of accepted roles with admin access")
I feel these oidc- flags could be parsed to see if they are valid.

2021-05-27 11:45 UTC, illume commented on backend/cmd/nebraska/auth/oidcauth.go
> +	rolesPath     string
It could maybe make sense to document these fields.

2021-05-27 11:53 UTC, illume commented on backend/cmd/nebraska/auth/oidcauth.go
> +				logger.Error().Str("request_id", requestID).AnErr("error", err).Msg("Can't Verify New ID Token")
I wonder if logging the Verify error would be useful info here?

2021-05-27 12:03 UTC, illume commented on backend/cmd/nebraska/auth/oidcauth.go
> +	cache := memcache.New(memcachegob.New())
What are the security implications for using memcache for the session store?

2021-05-27 12:19 UTC, illume commented
I see lots of documentation in the code, and the command line arguments are documented already :+1: Is updating the documentation (docs/authorization.md) in scope for this PR? 

Is there any manual testing you would like me to do? (I know we were talking about testing with Azure Active Directory.)

A PR description would be useful for passers by.

2021-05-27 12:38 UTC, illume commented on backend/cmd/nebraska/controller.go
> +			config.LoginURL = "http://localhost:8000/login"
I wonder if this default should be set somewhere else? Maybe in the command line args?

2021-05-31 11:07 UTC, joaquimrocha commented on frontend/package.json
> +    "react-redux": "^7.2.4",
Interesting. I used https://react-redux.js.org/introduction/getting-started since we are using react too, but I agree the toolkit looks better (1.5 years! jeez, that's like 15 years in real, non-js life).

2021-05-31 11:12 UTC, joaquimrocha commented
> I see lots of documentation in the code, and the command line arguments are documented already  Is updating the documentation (docs/authorization.md) in scope for this PR?
> 

Yes. I had mentioned to Santhosh that we need the docs.

I will address the frontend changes.

2021-05-31 15:18 UTC, joaquimrocha commented on frontend/src/js/stores/ApplicationsStore.ts
> +          case 401:
They are for now. It's an improvement over what we had before. But surely we should still find a better way to communicate when errors happen (for a different PR).

2021-05-31 15:24 UTC, joaquimrocha commented
I have updated the frontend part for including the redux changes.
@ashu8912 when you got some bandwidth (can be in another PR), please make the theme related changes so the tests run with static class names as René mentioned.
We should make the theme provider affect the whole app and not just the header, BTW.

2021-06-01 14:54 UTC, joaquimrocha requested changes
It's looking good. Left some comments.
Also, I think this section should be the 1st one after the noop dev one. And we should add another commit where the github auth prints a deprecation warning + delete github from the docs.

2021-06-01 14:54 UTC, joaquimrocha commented on docs/authorization.md
> +## Creating Roles
Separate with newline.

2021-06-01 14:54 UTC, joaquimrocha commented on docs/authorization.md
> +3. Click Save
I think these should go without empty lines in between.

2021-06-01 14:54 UTC, joaquimrocha commented on docs/authorization.md
> +4. After the admin role is created enable composite role to ON. In the Composite Roles section select the member role, In our case it is nebraska_member and click Add Selected.
Ditto.

2021-06-01 14:54 UTC, joaquimrocha commented on docs/authorization.md
> +  <img width="751" height="281" src="https://github.com/kinvolk/nebraska/blob/oidc/docs/images/keycloak-roles.gif">
You should omit the height to get its aspect ratio preserved + maybe using `width="100%"` is a good idea.
More importantly, use a relative path for the image.

2021-06-01 14:54 UTC, joaquimrocha commented on docs/authorization.md
> +4. Set `Valid Redirect URIs` to `http://localhost:8000/login/cb`.
Same thing about newlines.

2021-06-01 14:54 UTC, joaquimrocha commented on docs/authorization.md
> +3. Click `Save`
Ditto.

2021-06-01 14:54 UTC, joaquimrocha commented on docs/authorization.md
> +3. Go to `Role Mapping` tab and select `nebraska_admin` role and click on add selected to attach role to user. If you want to provide only member access access select the member role.
Ditto.

2021-06-01 14:54 UTC, joaquimrocha commented on docs/authorization.md
> +
Use only one newline.

2021-06-01 14:54 UTC, joaquimrocha commented on docs/authorization.md
> +# Preparing Keycloak as OIDC provider for nebraska
There should be an intro saying this is the recommended way for authenticating into Nebraska.

2021-06-01 14:54 UTC, joaquimrocha commented on docs/authorization.md
> +
Add one or two newlines, not 3.

2021-06-02 17:05 UTC, yolossn commented on docs/authorization.md
> +  <img width="751" height="281" src="https://github.com/kinvolk/nebraska/blob/oidc/docs/images/keycloak-roles.gif">
since we use the raw image URL from Github I am not sure if using a relative path will work here.

2021-06-02 17:13 UTC, joaquimrocha commented on docs/authorization.md
> +  <img width="751" height="281" src="https://github.com/kinvolk/nebraska/blob/oidc/docs/images/keycloak-roles.gif">
It does!

2021-06-03 19:35 UTC, krnowak commented on backend/cmd/nebraska/auth/oidcauth.go
> +	delete(oa.stateMap, state)
I think we should be more stringent in cleaning up the state map. There can be errors during authentication that will result in keeping some stale records in the state map. Too many of those errors and the map will eat too much memory.

2021-06-07 13:18 UTC, yolossn commented on backend/cmd/nebraska/auth/oidcauth.go
> +	loginRedirectURL := c.Request.URL.Query().Get("login_redirect_url")
Added a way to specify valid redirect URLs using command line args. Right now it is a direct string match, should we opt-in for a domain level check and not worry about what the redirect path is?

2021-06-07 13:21 UTC, joaquimrocha commented on backend/cmd/nebraska/auth/oidcauth.go
> +	loginRedirectURL := c.Request.URL.Query().Get("login_redirect_url")
If we could allow simple wildcards, then we could support both direct matches + prefixes (`https://kinvolk.io/*`).

2021-06-07 13:21 UTC, yolossn commented on backend/cmd/nebraska/auth/oidcauth.go
> +	cache := memcache.New(memcachegob.New())
We have been using Memcache as a session store for GitHub auth, AFAIK there isn't any.

2021-06-07 14:39 UTC, yolossn commented on backend/cmd/nebraska/auth/oidcauth.go
> +				logger.Error().Str("request_id", requestID).AnErr("error", err).Msg("Can't Verify New ID Token")
If any user is not able to access the endpoints due to auth we can match request_id in the response header and the logs to find the exact reason. Ideally, the probability of this case occurring is relatively low as token expiry is handled already. So It will be useful to know these errors.

2021-06-08 09:28 UTC, illume commented on backend/cmd/nebraska/auth/oidcauth.go
> +	loginRedirectURL := c.Request.URL.Query().Get("login_redirect_url")
Just be careful it does not allow things past like: https://kinvolk.io.evil.example.com/ 

It should always have a `/` on the end before the wildcard? So `https://kinvolk.io/*` would be ok, but `https://kinvolk.io*` would not be.

2021-06-08 09:33 UTC, illume commented on frontend/src/js/__tests__/Applications/__snapshots__/Item.spec.js.snap
> +          class="MuiGrid-root makeStyles-gridHeader-4 MuiGrid-container MuiGrid-justify-xs-space-between"
I'll create a new issue for this.

2021-06-08 09:39 UTC, illume commented on frontend/src/js/__tests__/Common/__snapshots__/SectionHeader.spec.js.snap
> -              role="presentation"
Not sure if removing this was intentional?

2021-06-08 09:42 UTC, illume commented on frontend/src/js/components/Main..tsx
> +      console.debug("Got config", config)
Maybe remove this console.debug now? The data is perhaps viewable in the redux dev tools.

2021-06-08 09:50 UTC, joaquimrocha commented on backend/cmd/nebraska/auth/oidcauth.go
> +	loginRedirectURL := c.Request.URL.Query().Get("login_redirect_url")
We're talking about a user defined parameter, so the user (and us) should take that into account when deploying, I don't think we can enforce some rule that prevents this while being flexible enough for all cases.

2021-06-08 09:51 UTC, illume commented on docs/authorization.md
> +# Deploying Nebraska for testing on local computer (OIDC authentication)
Cool! I'll try these instructions out.

2021-06-08 15:13 UTC, krnowak requested changes

2021-06-08 15:13 UTC, krnowak commented on backend/pkg/util/wildcard.go
> +func wildcardRuneMatch(pattern []rune, str []rune) bool {
Frankly speaking, I'm not a fan of a recursive nature of this function. Is there a chance that this function will be called with a string coming from a user (for example, from some specially crafted HTTP request)? If so, then I'd say that there is a risk of a stack exhaustion because of a too deep recursion when `str` is really super duper long. Maybe try converting it to an iterative version.

2021-06-08 15:13 UTC, krnowak commented on backend/pkg/util/wildcard_test.go
> +		patten         string
```suggestion
		pattern        string
```

2021-06-08 15:13 UTC, krnowak commented on backend/pkg/util/wildcard_test.go
> +		output := WildcardMatch(tc.patten, tc.str)
```suggestion
		output := WildcardMatch(tc.pattern, tc.str)
```

2021-06-09 06:34 UTC, yolossn commented on backend/pkg/util/wildcard.go
> +func wildcardRuneMatch(pattern []rune, str []rune) bool {
Even with an iterative version, a significant number of specially crafted HTTP requests can hog the server. 

Maybe we can reduce the scope of the match just to allow * operator at the end of a pattern (e.g., support http://localhost:8000/nebraska/* and not http://localhost:8000/nebraska/*/app/*). Then the logic will reduce to this. 

```go
func WildcardMatch(pattern string, str string) bool {
	i := strings.Index(pattern, "*")
	if i == -1 {
		return str == pattern
	}

	if len(str) > i {
		return str[:i] == pattern[:i]
	}
	return str == pattern[:i]
}

```
This should work for the majority of the use cases.

Cc: @joaquimrocha Is this what we wanted from the beginning?

2021-06-09 07:36 UTC, yolossn commented on backend/cmd/nebraska/auth/oidcauth.go
> +func (oa *oidcAuth) Authenticate(c *gin.Context) (teamID string, replied bool) {
Yes, a refactor was already under discussion. It will be done after Github auth is fully deprecated.

2021-06-09 15:08 UTC, joaquimrocha requested changes

2021-06-09 15:08 UTC, joaquimrocha commented on backend/pkg/util/wildcard.go
> +func wildcardRuneMatch(pattern []rune, str []rune) bool {
Assuming we're only allowing * wildcards, wouldn't it work and be simpler if we replace the pattern given URL with a regex expression and see if it matches?
Given URL `http://*.kinvolk.io/*` -> make it something like `pttrn := '^http://.*\.kinvolk\.io/.*'` + `matched, err := regexp.Match(pttrn, received_url)`

2021-06-10 03:21 UTC, yolossn commented on backend/pkg/util/wildcard.go
> +func wildcardRuneMatch(pattern []rune, str []rune) bool {
The issue with converting the given URL to regex is that we will have to take into account all Regex tokens and handle them. I think I found a package that supports * wildcard with a better simple solution, Refer [this](https://github.com/ryanuber/go-glob/blob/51a8f68e6c24dc43f1e371749c89a267de4ebc53/glob.go#L11)

2021-06-11 09:35 UTC, joaquimrocha commented on docs/authorization.md
> +3. Click Save
nitpick: Special names below were written using backquotes for highlighting. I think we should do the same in this group as well.

2021-06-11 09:37 UTC, joaquimrocha commented on docs/authorization.md
> +Now the rule to add the roles to the token is setup, the roles will be available in the key `http://kinvolk.io/roles`.
Should we add the corresponding roles path value for the nebraska parameter in this and KeyCloak's docs?
Or are the deployment_docs enough?

2021-06-11 12:14 UTC, yolossn commented on docs/authorization.md
> +Now the rule to add the roles to the token is setup, the roles will be available in the key `http://kinvolk.io/roles`.
Added a note in Deploying Nebraska with OIDC section

2021-06-11 14:33 UTC, krnowak commented on backend/cmd/nebraska/auth/oidcauth.go
> +func (oa *oidcAuth) Authenticate(c *gin.Context) (teamID string, replied bool) {
Cool, thanks for confirming.

2021-06-11 14:38 UTC, krnowak approved these changes
One nitpick, otherwise ok.

2021-06-11 14:38 UTC, krnowak commented on backend/cmd/nebraska/auth/oidcauth.go
> +			logger.Debug().Str("message", fmt.Sprintf("Deleting expired key %s from sate map", key))
```suggestion
			logger.Debug().Str("message", fmt.Sprintf("Deleting expired key %s from state map", key))
```

2021-06-11 22:02 UTC, joaquimrocha approved these changes

2021-06-11 22:15 UTC, joaquimrocha commented
Thanks to everyone involved!
I have rebased and will merge now. Cheers!

2021-06-11 22:15 UTC, merged