Add sort to instance list
kinvolk/nebraska pull request #378
Opened 2021-05-24 17:40 UTC by ashu8912

# [Title: describe the change in one sentence]
Adds sort filter to instances list

## How to use
Go to instance list view and apply the various sort filters available, also use the sortOrder filter to change in what order you want the sorted data to appear(desc or asc)

## Testing done
Yes

2021-05-25 02:08 UTC, yolossn commented on backend/pkg/api/instances.go
> +		Order(columnToSortExpression).
Can you check if any indexes will be required for this ? 
Reference: https://www.postgresql.org/docs/8.3/indexes-ordering.html

2021-05-31 11:02 UTC, joaquimrocha requested changes
I'd like to understand whether it's too complicated to add the sorting triggered from the column title cell's up/down buttons, as we have for Headlamp. I know that the filtering in Headlamp is client-side ATM, so this one needs more changes, but in terms of UX that's what was expected from the issue (#350 ).

2021-05-31 16:30 UTC, ashu8912 commented
![Screenshot from 2021-05-31 21-59-28](https://user-images.githubusercontent.com/30126128/120221191-94d91800-c25b-11eb-8792-149a10eb20e1.png)
![Screenshot from 2021-05-31 21-59-44](https://user-images.githubusercontent.com/30126128/120221200-97d40880-c25b-11eb-8a9d-36fe1b5ddc2b.png)

2021-05-31 16:31 UTC, ashu8912 commented
![Screenshot from 2021-05-31 22-00-53](https://user-images.githubusercontent.com/30126128/120221275-bf2ad580-c25b-11eb-893b-29ba15707c69.png)
![Screenshot from 2021-05-31 22-01-04](https://user-images.githubusercontent.com/30126128/120221277-c05c0280-c25b-11eb-9968-44064aba24ce.png)

2021-06-01 09:12 UTC, joaquimrocha commented
@ashu8912 , from the screenshots, I think the UX needs to be improved. Let's look into using the up/down arrows on the SimpleTable (take it and adapt it from Headlamp is needed) as we discussed on Slack.

2021-06-08 15:55 UTC, krnowak commented on backend/pkg/api/instances.go
> +	SortOrder     int    `json:"sort_order"`
Maybe it would be better to have a separate enumeration for sort order like:
```go
type sortOrder int

const (
	sortOrderAsc sortOrder = iota
	sortOrderDesc
)

func sortOrderFromString(str string) (sortOrder, error) {
	…
}
```

That way, you would have a clearly defined allowed values for the sort order parameter (right now `1` is for descending sort, anything else is ascending sort), and you could avoid some magic numbers below.

2021-06-15 12:13 UTC, ashu8912 commented
![Screenshot from 2021-06-15 17-43-11](https://user-images.githubusercontent.com/30126128/122050606-3edea580-ce01-11eb-8594-cccfc984b7c7.png)

2021-06-15 13:53 UTC, illume commented on backend/cmd/nebraska/controller.go
> +	p.SortFilter = sortFilter
I guess this could just be this? `p.SortFilter = c.Query("sort")`

2021-06-15 14:09 UTC, illume commented on frontend/src/js/components/Instances/List.tsx
> +      Object.keys(_filters).length !== 0 ? _filters : { status: '', version: '', sort: 'id' };
Sorting by id by default?

2021-06-16 08:19 UTC, yolossn commented on backend/pkg/api/instances.go
> +	}
This can also be moved below the `existsInInstanceAppTable` conditional block.

2021-06-16 08:20 UTC, yolossn commented on backend/pkg/api/instances.go
>  	}
Maybe move the instancesQuery below the existsInInstanceAppTable conditional block for better readability

2021-06-16 08:24 UTC, yolossn commented on backend/pkg/api/instances.go
> +		return InstancesWithTotal{}, fmt.Errorf("The sort filter %s is invalid", sortFilter)
The error message will be wrong in the case there was an error returned by `checkIfColumnExistInTableQuery`

2021-06-16 08:43 UTC, yolossn commented on backend/pkg/api/instances.go
> +	}
this can just be 
``` go
if val,ok:=sortFilterMap[sortFilterNumericValue];ok{
   return sortFilterMap[sortFilterNumericValue]
}
return sortFilterMap[id]
```

2021-06-16 08:50 UTC, yolossn commented on backend/pkg/api/instances.go
> +	return sortOrder(val), err
Here the returned value can be any `int` and there is a chance the value will not match both the cases in

```go
               if sortOrder == sortOrderAsc {
			instancesQuery = instancesQuery.Order(goqu.I(sortFilter).Asc().NullsLast())
		} else if sortOrder == sortOrderDesc {
			instancesQuery = instancesQuery.Order(goqu.I(sortFilter).Desc().NullsLast())
		}
```

2021-06-16 09:01 UTC, yolossn commented on backend/pkg/api/instances.go
> +	return sortOrder(val), err
Is there a need to return an error? In this case, the sortOrder will default to `sortOrderAsc`.

2021-06-16 10:50 UTC, joaquimrocha requested changes

2021-06-16 10:50 UTC, joaquimrocha commented on frontend/src/js/components/Instances/List.tsx
> +  const [sortOrder, setSortOrder] = React.useState(false);
The code would be more self-explainatory if this was e.g. `isAscSortOrder`, `setIsAscSortOrder` = false|true

2021-06-16 10:50 UTC, joaquimrocha commented on frontend/src/js/components/Instances/List.tsx
> +      Object.keys(_filters).length !== 0 ? _filters : { status: '', version: '', sort: 'id' };
Yeah, maybe sorting by last update check by default would be better.

2021-06-16 10:50 UTC, joaquimrocha commented on frontend/src/js/components/Instances/List.tsx
> +                <Grid item md={3}>
Is this left over from your original approach?

2021-06-16 10:50 UTC, joaquimrocha commented on frontend/src/js/components/Instances/List.tsx
> +                <Grid item md={9}>
Is this left over from your original approach?

2021-06-16 10:50 UTC, joaquimrocha commented on frontend/src/js/components/Instances/List.tsx
> +    addQuery({ sort: sortQuery, sortOrder: Number(sortOrder) });
I'd prefer the sort values to be human readable, like `sort=name` or `sort=last-check`, etc.
This can be only in the frontend of course, where we match a number and do the request to the backend with that.

2021-06-16 17:37 UTC, ashu8912 commented on backend/pkg/api/instances.go
> +		return InstancesWithTotal{}, fmt.Errorf("The sort filter %s is invalid", sortFilter)
I have moved the error checking above this block

2021-06-17 11:08 UTC, yolossn commented on backend/pkg/api/instances.go
> +	}
Duplicate error handling block can be removed.

2021-06-18 07:17 UTC, yolossn commented on backend/pkg/api/instances.go
> +func (api *API) getInstanceFromApp(instanceIDOfApp string) (*Instance, error) {
This can be 
```
func (api *API) getInstanceFromID(instanceID string) (*Instance, error) {
```

2021-06-22 10:32 UTC, yolossn commented on backend/pkg/api/instances.go
> +func (api *API) getInstanceFromApp(instanceIDOfApp string) (*Instance, error) {
@ashu8912 looks like this got missed.

2021-06-22 10:41 UTC, yolossn commented on backend/pkg/api/instances.go
> +
small nit, the empty line is not needed here.

2021-06-22 11:05 UTC, ashu8912 commented on backend/pkg/api/instances.go
> +func (api *API) getInstanceFromApp(instanceIDOfApp string) (*Instance, error) {
fixed

2021-06-22 11:06 UTC, ashu8912 commented on backend/pkg/api/instances.go
> +
thanks,fixed

2021-06-22 16:09 UTC, krnowak commented on backend/pkg/api/instances.go
> +		}
Shouldn't this be something to get with a single query that joins instance apps table and instances table? Or maybe with two queries, where one gets the instance apps, and second gets all the interesting instances? Because right now it looks like we are doing 1 + N queries here.

2021-06-23 05:56 UTC, ashu8912 commented on backend/pkg/api/instances.go
> +		}
@krnowak yes I was also thinking about a join query at the beginning but the problem is we have been doing such queries almost everywhere and this 1+N querying is not something specific to this patch.

we already have an issue with that https://github.com/kinvolk/nebraska/issues/228, I didn't change it to a JOIN query because it was moving a lot of code pieces, here the plan was to add a separate patch that tackles all these query optimization things.

2021-06-23 06:00 UTC, ashu8912 commented on backend/pkg/api/instances.go
> +		}
Also the table instance and instance_applications are huge so things like JOIN would be costly this is something we still need to investigate

2021-06-23 16:18 UTC, krnowak commented on backend/pkg/api/instances.go
> +		}
Heh, I even forgot that I already filed an issue about it. So I'm going to let it slide another time then. :)

2021-06-23 16:26 UTC, krnowak requested changes
Some minor nits, looks good otherwise.

2021-06-23 16:26 UTC, krnowak commented on frontend/src/js/utils/helpers.ts
> +export const InstanceSortFilters:{
This one could use a comment like the `ARCHES` constant above has.

2021-06-23 16:26 UTC, krnowak commented on backend/pkg/api/instances.go
> +)
Could these constants be of a separate type, so they are not accidentally misused as some random number?

2021-06-24 09:25 UTC, joaquimrocha commented
I have tested this again but it still doesn't sort the instances correctly if they have an alias.
Test:
1. Go to the instances list in some group, and select an instance in the middle of the table;
2. Go to the 3-dot menu and select Rename. Rename the instance as `zzz`.
3. Do the same with another instance from the middle of the instance list but rename it as `aaa`
4. Use the instance ID column's sorting buttons to sort it.

Expected outcome: the `aaa` instance shows up as the first one, and the `zzz` as the last one, when sorting ascendently. And the opposite when sorting in decending order.

Actual outcome: those instances are not shown at the first/last places.

Also, I've noticed I don't see the aaa/zzz instances with these names at all after pressing sort.

2021-07-01 09:43 UTC, joaquimrocha commented on frontend/src/js/components/Instances/List.tsx
> +                        'aria-label': 'previous page'
This and other simimlar changes shouldn't be in the PR. Is husky/pretty not handling this?

2021-07-01 13:32 UTC, merged