backend/cmd: integrate gin-swagger to backend server
kinvolk/nebraska pull request #397
Opened 2021-06-21 19:51 UTC by abraarsyed

gin-swagger is api documentation tool, setup to backend server through swag init (CLI)

Signed-off-by: abraarsyed <abraar.syed01@gmail.com>

# [Title: describe the change in one sentence]

Add Gin-Swagger to backend Go server

# [ describe the change in 1 - 3 paragraphs ]

Gin Swagger is an API documentation tool, this commit integrates this tool with the existing backend server. The docs folder has been generated using Swag CLI (swag init command), post which the docs are linked to the server. 

## How to use

[ describe what reviewers need to do in order to validate this PR ]

1. Download the following:

`go get -u github.com/swaggo/swag/cmd/swag`
`go get -u github.com/swaggo/gin-swagger`
`go get -u github.com/swaggo/files`

2. Run the server:

`make run-backend`

3. Visit following link in the browser:

`http://localhost:8000/swagger/swagger.index.html`

## Testing done

[Describe the testing you have done before submitting this PR. Please include both the commands you issued as well as the output you got.]

I have done manual testing for it, please guide me if there is any specific test to be written for this or if I have missed out anything

2021-06-22 10:03 UTC, yolossn commented on backend/cmd/nebraska/nebraska.go
> +	docs.SwaggerInfo.Host = "localhost:8000"
```suggestion
	docs.SwaggerInfo.Host = *nebraskaURL
```

2021-06-22 10:07 UTC, yolossn commented on backend/cmd/nebraska/nebraska.go
> +	"github.com/kinvolk/nebraska/backend/cmd/userctl/docs" // docs is generated by Swag CLI, you have to import it.
Please follow [golang-standards/project-layout ](https://github.com/golang-standards/project-layout) and move swagger related files to /api folder ([Refer](https://github.com/golang-standards/project-layout#api)).

2021-06-29 15:30 UTC, abraarsyed commented on backend/cmd/nebraska/nebraska.go
> +	"github.com/kinvolk/nebraska/backend/cmd/userctl/docs" // docs is generated by Swag CLI, you have to import it.
Hey @yolossn, I have got most of the things working and made the required code review changes but this is the last part remaining. 

Can you please point me out an example, maybe somewhere in the same project itself on how to move external project related files to /api folder. I tried doing it but I am getting error related to `use of package without selector`. I am new to Go lang so probably making some mistake wrt packages in Go lang.

Can you provide me bit of guidance please? Thank you

2021-06-29 17:01 UTC, abraarsyed commented on backend/cmd/nebraska/nebraska.go
> +	docs.SwaggerInfo.Host = "localhost:8000"
Hey @yolossn, as suggested, I changed `localhost:8000` to `*nebraskaURL` and it worked fine but then later when I wrote the API docs for one of the controller function which you had given, I realised that nebraskaURL variable holds the `http://` part as well as part of the string so swagger tries to add `http://` twice so I had to remove it and keep it back to `localhost:8000`. So this is okay if I use `localhost:8000` here or create new variable or perform string operations on nebraskaURL and remove the `http://` part? What do you suggest?

2021-06-29 17:14 UTC, yolossn commented on backend/cmd/nebraska/nebraska.go
> +	docs.SwaggerInfo.Host = "localhost:8000"
You can use the [string.TrimPrefix](https://golang.org/pkg/strings/#TrimPrefix) function to handle both `http://` and `https://` like this  example.
```go
strings.TrimPrefix(strings.TrimPrefix(*nebraskaURL,"https://"),"http://")
```

2021-06-29 17:24 UTC, yolossn commented on backend/cmd/nebraska/nebraska.go
> +	"github.com/kinvolk/nebraska/backend/cmd/userctl/docs" // docs is generated by Swag CLI, you have to import it.
1. In the backend folder create an api folder. 
2. Move the contents of `cmd/userctl/docs` contents to `backend/api` folder.
3. Change the package name to `api`.

2021-06-29 17:39 UTC, abraarsyed commented on backend/cmd/nebraska/nebraska.go
> +	"github.com/kinvolk/nebraska/backend/cmd/userctl/docs" // docs is generated by Swag CLI, you have to import it.
Thank you @yolossn for such quick responses. So, some amount of my doubt got cleared after reading your response. I have one more question, in my last commit: a5797ae873fedbf374f995d63da9a3afd20546d4, I have moved the docs to separate folder, i.e., backend/docs. Is that okay? Or should I change the name of the folder to /api? 

Because the docs folder got autogenerated when I executed the swag init command from the main backend location so I want to understand if I should change folder name to `api` or is it  okay if I keep `docs` itself?

2021-06-29 17:42 UTC, abraarsyed commented on backend/cmd/nebraska/nebraska.go
> +	docs.SwaggerInfo.Host = "localhost:8000"
And it is done :D 24d3ee4b5184aaa45e74e04d498e8adf12c025d6

2021-06-30 03:27 UTC, yolossn commented on backend/cmd/nebraska/nebraska.go
> +	"github.com/kinvolk/nebraska/backend/cmd/userctl/docs" // docs is generated by Swag CLI, you have to import it.
You can specify the output folder in `swag init` command [Refer](https://github.com/swaggo/swag#swag-cli).

2021-06-30 08:34 UTC, abraarsyed commented on backend/cmd/nebraska/nebraska.go
> +	"github.com/kinvolk/nebraska/backend/cmd/userctl/docs" // docs is generated by Swag CLI, you have to import it.
Hey @yolossn, wont it be conflicting? Since we already have `github.com/kinvolk/nebraska/backend/pkg/api` imported in `nebraska.go` and if I add `/backend/api`, it will conflict right, since both are api?

2021-06-30 09:25 UTC, yolossn commented on backend/cmd/nebraska/nebraska.go
> +	"github.com/kinvolk/nebraska/backend/cmd/userctl/docs" // docs is generated by Swag CLI, you have to import it.
You can use an alias to the import if the package name is the same, [Refer](https://stackoverflow.com/questions/10408646/how-to-import-and-use-different-packages-of-the-same-name). Go ahead and create `api` sub folder in `backend` folder and use the import alias to handle the name conflict.

2021-06-30 09:46 UTC, yolossn commented on backend/cmd/nebraska/controller.go
> +// @Param team_id query string false "Team ID"
In this case `team_id` is not a query param, please remove it.

2021-06-30 09:48 UTC, yolossn commented on backend/cmd/nebraska/controller.go
> +// @Failure default {string} string "error"
Can this be combined into a single line ?
```go
// @Failure 400,404,500,default {string} string "error"
```

2021-06-30 09:48 UTC, yolossn commented on backend/cmd/nebraska/controller.go
> +// @Description Get paginated information of all applications under a given team ID
```suggestion
// @Description Get paginated information of all applications
```

2021-06-30 14:04 UTC, abraarsyed commented on backend/cmd/nebraska/controller.go
> +// @Param team_id query string false "Team ID"
Done! d02b744418fa494a4ee220ca5d8c6ce702e33930

2021-06-30 14:04 UTC, abraarsyed commented on backend/cmd/nebraska/controller.go
> +// @Failure default {string} string "error"
Done! d02b744418fa494a4ee220ca5d8c6ce702e33930

2021-06-30 14:04 UTC, abraarsyed commented on backend/cmd/nebraska/controller.go
> +// @Description Get paginated information of all applications under a given team ID
Done! d02b744418fa494a4ee220ca5d8c6ce702e33930

2021-06-30 16:50 UTC, yolossn requested changes
Few Nitpicks, Looks good otherwise. Can you add the `swag init` command to the make file? It will make it easy for other developers. 

Example:
```make
.PHONY: backend/tools/swagger
backend/tools/swagger:
	go get -u github.com/swaggo/swag/cmd/swag;

.PHONY: swagger
codegen: backend/tools/swagger
	swag init --output backend/api;
```

2021-06-30 16:50 UTC, yolossn commented on backend/cmd/nebraska/nebraska.go
> +	swagger "github.com/kinvolk/nebraska/backend/api" // swagger is generated by Swag CLI, you have to import it.
```suggestion
	swagger "github.com/kinvolk/nebraska/backend/api" 
```

2021-06-30 16:50 UTC, yolossn commented on backend/cmd/nebraska/nebraska.go
> +	// programmatically set swagger info
```suggestion
	// Gin Swagger setup
```

2021-07-01 08:50 UTC, abraarsyed commented on backend/cmd/nebraska/nebraska.go
> +	swagger "github.com/kinvolk/nebraska/backend/api" // swagger is generated by Swag CLI, you have to import it.
Done! 665d7c493aace08884c60a88199fa1a968de7a66

2021-07-01 08:50 UTC, abraarsyed commented on backend/cmd/nebraska/nebraska.go
> +	// programmatically set swagger info
Done! 665d7c493aace08884c60a88199fa1a968de7a66

2021-07-01 08:51 UTC, abraarsyed commented
> Few Nitpicks, Looks good otherwise. Can you add the `swag init` command to the [make](https://github.com/kinvolk/nebraska/blob/master/Makefile) file? It will make it easy for other developers.
> 
> Example:
> 
> ```makefile
> .PHONY: backend/tools/swagger
> backend/tools/swagger:
> 	go get -u github.com/swaggo/swag/cmd/swag;
> 
> .PHONY: swagger
> codegen: backend/tools/swagger
> 	swag init --output backend/api;
> ```

Done! 665d7c493aace08884c60a88199fa1a968de7a66

2021-07-02 04:24 UTC, yolossn commented on Makefile
> +	cd backend && swag init -g cmd/userctl/main.go -o api
```suggestion
swagger-init: swagger-install
	cd backend && swag init -g cmd/userctl/main.go -o api
```

2021-07-02 04:35 UTC, yolossn commented on backend/cmd/nebraska/nebraska.go
> +	swagger.SwaggerInfo.Description = "This is a sample server for nebraska"
```suggestion
	swagger.SwaggerInfo.Description = "Nebraska Swagger documentation"
```

2021-07-02 04:37 UTC, yolossn commented
Few other nits, otherwise LGTM.

2021-07-02 05:52 UTC, abraarsyed commented on backend/cmd/nebraska/nebraska.go
> +	swagger.SwaggerInfo.Description = "This is a sample server for nebraska"
Done! bf4c92cac4e937f248854634f8bfa49d3b389207

2021-07-02 05:53 UTC, abraarsyed commented on Makefile
> +	cd backend && swag init -g cmd/userctl/main.go -o api
Done! bf4c92cac4e937f248854634f8bfa49d3b389207

2021-07-02 05:53 UTC, abraarsyed commented
> Few other nits, otherwise LGTM.

Thank you @yolossn, I have fixed the nitpicks mentioned. Can you help me merge this PR if the final code looks good to you?

2021-07-02 07:01 UTC, yolossn commented
Thank you @abraarsyed, Will merge it after getting approval from @joaquimrocha.

2021-07-02 09:29 UTC, joaquimrocha approved these changes
LGTM. Thanks @abraarsyed and @yolossn !

2021-07-02 09:29 UTC, merged