chart: Add OIDC auth mode support to helm chart
kinvolk/nebraska pull request #404
Opened 2021-06-30 08:34 UTC by yolossn

This patch adds changes to the helm chart to support
oidc auth mode.

Signed-off-by: Santhosh Nagaraj S <santhosh@kinvolk.io>

2021-06-30 08:47 UTC, knrt10 requested changes
Some NITS

2021-06-30 08:47 UTC, knrt10 commented on charts/nebraska/templates/secrets.yaml
> +  oidcSessionCryptKey: {{required "A valid is 'sessionCryptKey' required when using oidc authentication" .Values.config.auth.oidc.sessionCryptKey |toString | b64enc }}
It should be `A valid 'name'` is. i.e  `is` used incorrectly.

2021-06-30 08:47 UTC, knrt10 commented on charts/nebraska/README.md
> +| `config.auth.oidc.sessionCryptKey`                    | Session key used for encrypting sessions in cookies used for storing OIDC info, will be generated if none is passed | `nil`
Can this be rephrased? It sounds a bit confusing. Eg `used for` used in a same sentence twice.

2021-06-30 08:47 UTC, knrt10 commented on charts/nebraska/templates/deployment.yaml
> +              {{- if and .Values.config.auth.github.readWriteTeams}}
`and` operator is not needed as there is no comparrision

2021-06-30 08:47 UTC, knrt10 commented on charts/nebraska/templates/deployment.yaml
> +            - name: "NEBRASKA_OIDC_CLIENT_ID"
Any specific reason why secret name has `NEBRASKA` prefix and key does not?

2021-06-30 09:37 UTC, yolossn commented on charts/nebraska/templates/deployment.yaml
> +            - name: "NEBRASKA_OIDC_CLIENT_ID"
The application requires the env vars to have a `NEBRASKA` prefix.

2021-06-30 14:58 UTC, knrt10 requested changes
Small indentation change. And same for other occurances in this PR. Rest LGTM

2021-06-30 14:58 UTC, knrt10 commented on charts/nebraska/templates/deployment.yaml
> +              {{- if .Values.config.auth.github.readWriteTeams}}
```suggestion
              {{- if .Values.config.auth.github.readWriteTeams }}
```

2021-07-02 03:24 UTC, knrt10 approved these changes

2021-07-02 09:26 UTC, joaquimrocha commented on charts/nebraska/templates/secrets.yaml
> +{{- if or ($useDbPassword) ($useOidcAuth) ($useGhAuth) }}
I am not familiar with Helm chart's templates but this caught my eye, and the docs suggest you can only apply it to 2 values: https://helm.sh/docs/chart_template_guide/function_list/#or

2021-07-02 10:11 UTC, yolossn commented on charts/nebraska/templates/secrets.yaml
> +{{- if or ($useDbPassword) ($useOidcAuth) ($useGhAuth) }}
Fixed.

2021-07-02 10:15 UTC, yolossn commented
Bump the appVersion after the release and then merge.

2021-07-05 14:09 UTC, mkilchhofer reviewed
Already works properly (used DexIdp with Github connector). Although there still are severals nits :-) Feel free to consider my comments.

2021-07-05 14:09 UTC, mkilchhofer commented on charts/nebraska/README.md
> +| `config.auth.oidc.sessionCryptKey`                    | Session key used for encrypting sessions in cookies to store OIDC info, will be generated if none is passed | `nil`
> "will be generated if none is passed"

This conflicts with the "required" keyword in the secrets.yaml file.

2021-07-05 14:09 UTC, mkilchhofer commented on charts/nebraska/templates/secrets.yaml
> +{{- if or (or $useDbPassword $useOidcAuth) ($useGhAuth) }}
```suggestion
{{- if or $useDbPassword $useOidcAuth $useGhAuth }}
```
The keyword `or` supports multiple arguments. Only examples shows 2 :-)

2021-07-05 14:09 UTC, mkilchhofer commented on charts/nebraska/templates/secrets.yaml
> +{{- $useOidcAuth := (eq .Values.config.auth.mode "oidc")}}
```suggestion
{{- $useGhAuth := eq .Values.config.auth.mode "github" }}
{{- $useOidcAuth := eq .Values.config.auth.mode "oidc" }}
```

2021-07-05 14:09 UTC, mkilchhofer commented on charts/nebraska/templates/secrets.yaml
> +  oidcSessionCryptKey: {{required "A valid 'sessionCryptKey' is required when using oidc authentication" .Values.config.auth.oidc.sessionCryptKey |toString | b64enc }}
```suggestion
  oidcClientID: {{ required "A valid 'clientId' is required when using oidc authentication" .Values.config.auth.oidc.clientID | toString | b64enc }}
  oidcClientSecret: {{ required "A valid 'clientSecret' is required when using oidc authentication" .Values.config.auth.oidc.clientSecret | toString | b64enc }}
  oidcSessionAuthKey: {{ required "A valid 'sessionAuthKey' is required when using oidc authentication" .Values.config.auth.oidc.sessionAuthKey | toString | b64enc }}
  oidcSessionCryptKey: {{ required "A valid 'sessionCryptKey' is required when using oidc authentication" .Values.config.auth.oidc.sessionCryptKey | toString | b64enc }}
```
Add spaces to be consistent across existing code style

2021-07-05 14:09 UTC, mkilchhofer commented on charts/nebraska/values.yaml
> +      logoutURL:
Missing in README

2021-07-05 14:15 UTC, mkilchhofer commented
Oh and there is something additional I observed. The container image 
```console
$ kubectl get po nebraska-69bcd477f6-mh7vc -o jsonpath='{.spec.containers[].image}{"\n"}'
quay.io/flatcar/nebraska:2.4.0
```
still contains the "dirty" flag:
![image](https://user-images.githubusercontent.com/7290987/124484808-2a604e00-ddac-11eb-9842-a1a43a8e93bc.png)

2021-07-05 14:18 UTC, yolossn commented on charts/nebraska/templates/secrets.yaml
> +{{- if or (or $useDbPassword $useOidcAuth) ($useGhAuth) }}
TIL

2021-07-05 14:38 UTC, joaquimrocha commented
@mkilchhofer , I am aware of the dirty flag. I think there must be a build artifact causing this. Once I solve it, I can create a 2.4.1 release.

2021-07-05 14:43 UTC, yolossn commented
@mkilchhofer, I have addressed the requested changes. Can you review the changes?

2021-07-05 17:28 UTC, mkilchhofer requested changes
More nits 😄 . Maybe we should generate the README (with helm-docs) and remove the manual indentation.

2021-07-05 17:28 UTC, mkilchhofer commented on charts/nebraska/templates/deployment.yaml
> +            - "-oidc-issuer-url={{ .Values.config.auth.oidc.issuerURL }}"
Maybe it would make more sense to wrap every command line option with the keyword `with` instead of `if`. Then we do not need to write the values path twice. WDYT? Applies also for the following lines.
```suggestion
              {{- with .Values.config.auth.oidc.issuerURL }}
            - "-oidc-issuer-url={{ . }}"
```

2021-07-05 17:28 UTC, mkilchhofer commented on charts/nebraska/templates/deployment.yaml
> +                  key: oidcSessionCryptKey
```suggestion
              {{- if .Values.config.auth.oidc.sessionAuthKey }}
            - name: "NEBRASKA_OIDC_SESSION_SECRET"
              valueFrom:
                secretKeyRef:
                  name: {{ include "nebraska.fullname" . }}
                  key: oidcSessionAuthKey
              {{- end }}
              {{- if .Values.config.auth.oidc.sessionCryptKey }}
            - name: "NEBRASKA_OIDC_SESSION_CRYPT_KEY"
              valueFrom:
                secretKeyRef:
                  name: {{ include "nebraska.fullname" . }}
                  key: oidcSessionCryptKey
              {{- end }}
```

2021-07-05 17:28 UTC, mkilchhofer commented on charts/nebraska/templates/secrets.yaml
> +  oidcSessionAuthKey: {{ "A valid 'sessionAuthKey' is required when using oidc authentication" .Values.config.auth.oidc.sessionAuthKey | toString | b64enc }}
```suggestion
    {{- with .Values.config.auth.oidc.sessionAuthKey }}
  oidcSessionAuthKey: {{ . | toString | b64enc }}
```

2021-07-05 17:28 UTC, mkilchhofer commented on charts/nebraska/templates/secrets.yaml
> +  oidcSessionCryptKey: {{ "A valid 'sessionCryptKey' is required when using oidc authentication" .Values.config.auth.oidc.sessionCryptKey | toString | b64enc }}
```suggestion
    {{- with .Values.config.auth.oidc.sessionCryptKey }}
  oidcSessionCryptKey: {{ . | toString | b64enc }}
```

2021-07-05 17:28 UTC, mkilchhofer commented on charts/nebraska/README.md
> +| `config.auth.github.enterpriseURL`                    | Base URL of the enterprise instance if using GHE                                                                                     | `nil`
This line here still misses a trailing `|`
```suggestion
| `config.auth.github.enterpriseURL`                    | Base URL of the enterprise instance if using GHE                                                                                     | `nil`                                                                   |
```

2021-07-07 08:03 UTC, yolossn commented on charts/nebraska/templates/deployment.yaml
> +            - "-oidc-issuer-url={{ .Values.config.auth.oidc.issuerURL }}"
I have made this change for the OIDC values alone for now and skipped it for the GitHub values as it will be removed eventually.

2021-07-07 08:25 UTC, yolossn commented
@mkilchhofer, I have addressed the requested changes. Can you take another look?

2021-07-07 11:49 UTC, mkilchhofer approved these changes
LGTM. deployment to my environment (github/dex) with the latest update works without issues :-)

2021-07-07 11:51 UTC, merged

2021-07-07 11:51 UTC, joaquimrocha commented
Great stuff! Thanks @mkilchhofer and @yolossn !