frontend: Implement v4 design
kinvolk/nebraska pull request #413
Opened 2021-07-05 07:45 UTC by ashu8912

- [x] Group Forms design updates 
- [ ]  App view design  
- [ ] App details view  

fixes #402

2021-07-05 09:12 UTC, illume commented on frontend/src/js/components/Groups/EditDialog.tsx
> +          <TabPanel
There's some notes on a11y stuff and Tabs here: https://material-ui.com/components/tabs/#accessibility

2021-07-05 09:14 UTC, illume commented on frontend/src/js/components/Groups/EditDialog.tsx
> +function GroupDetailsForm(props: { channels: Channel[] }) {
Probably worth separating the components into their own files?

- `EditDialog/EditDialog.tsx`
- `EditDialog/GroupDetailsForm.tsx`
- `EditDialog/GroupPolicyForm.tsx`
- etc...

2021-07-08 20:23 UTC, joaquimrocha requested changes
Hi Ashu,

I left a few comments.
I tested the PR and noticed as well that the group's details were not loaded into the Details tab (the policy tab seemed fine).

I appreciate that you implemented already the sorting, but I think the design specs were not clear enough, and its behavior needs to be refined. So I'd rather keep the sorting out of this PR and focus on the group editing form for now.

2021-07-08 20:23 UTC, joaquimrocha commented on frontend/src/js/components/Groups/List.tsx
> +import EditDialog from './EditDialog/EditDialog';
Should the file holding the EditDialog be `index.tsx` so we'd avoid this? Ditto for the rest of the examples like this.

2021-07-08 20:23 UTC, joaquimrocha commented on frontend/src/js/components/Applications/Item.tsx
> +                      <label htmlFor="sort-filter">Sort by</label>
This label is not translatable.

2021-07-08 20:23 UTC, joaquimrocha commented on frontend/src/js/components/Applications/ApplicationItemGroupsList.tsx
> +      case 'Instances Count':
We shouldn't rely on labels for logic decision (they should also be changed to be translatable and then this will fail).

2021-07-08 20:23 UTC, joaquimrocha commented on frontend/src/js/components/Common/Filters/GroupSortSelect.tsx
> +        <label htmlFor="sort-filter">Sort by</label>
Same comment as before.

2021-07-08 20:23 UTC, joaquimrocha commented on frontend/src/js/components/Applications/ApplicationItemGroupsList.tsx
> +      case 'All':
"Sorting by All" can be confusing. Also the logic here looks very similar to the instance count one.
BTW, the sorting should be "Name" (and we sort alphabetically), and "Instance count".

2021-07-08 20:23 UTC, joaquimrocha commented on frontend/src/js/components/Common/ListHeader.tsx
> +        <Box display="flex">
You're adding a Box to a Grid. I didn't check if there are complaints, but maybe we should use Grid items and tweak how they behave?

2021-07-08 20:23 UTC, joaquimrocha commented on frontend/src/js/components/Groups/List.tsx
> +            <Icon icon={filterIcon} />
I'd like the filter icon to change to the "remove filter" if we have enabled the filter.

2021-07-08 20:23 UTC, joaquimrocha commented on frontend/src/js/components/Groups/List.tsx
> +    <Grid item>
Is this going to be added to a grid?

2021-07-08 20:23 UTC, joaquimrocha commented on frontend/src/js/components/Groups/EditDialog/EditDialog.tsx
> +      group.policy_update_timeout.split(' ');
This commit should be squashed with the commit that first adds the tabs.

2021-07-09 10:15 UTC, ashu8912 commented on frontend/src/js/components/Groups/List.tsx
> +import EditDialog from './EditDialog/EditDialog';
fixed

2021-07-09 10:16 UTC, ashu8912 commented on frontend/src/js/components/Applications/Item.tsx
> +                      <label htmlFor="sort-filter">Sort by</label>
I have removed the sort pr from this PR

2021-07-14 07:43 UTC, illume commented on frontend/src/js/components/Groups/EditDialog/index.tsx
> +    let packageFunctionCall;
Could this be `const packageFunctionCall = applicationsStore.createGroup(data);` ?

2021-07-14 07:45 UTC, illume commented on frontend/src/js/components/Groups/EditDialog/index.tsx
> +    const data: {
Could `data` be typed as a Group so the type checker could be used below? Then the typechecker doesn't need to be turned off with `data as Group`.

2021-07-14 07:50 UTC, illume commented on frontend/src/js/components/Groups/EditDialog/index.tsx
> +    const data: {
Ah, oops. This was copied from the other file. Please ignore that comment then.

2021-07-14 07:50 UTC, illume commented on frontend/src/js/components/Groups/EditDialog/index.tsx
> +    let packageFunctionCall;
Ah, oops. This was copied from the other file. Please ignore that comment then.

2021-07-16 05:35 UTC, illume commented
> I tested the PR and noticed as well that the group's details were not loaded into the Details tab (the policy tab seemed fine).

I see this issue still...

<img width="1440" alt="Screenshot 2021-07-16 at 07 29 56" src="https://user-images.githubusercontent.com/9541/125897153-5ff6b811-5def-4d54-a10e-ff90e30cfe82.png">

2021-07-16 05:35 UTC, illume requested changes
Editing Group does not have data in the Details tab.

2021-07-16 16:32 UTC, illume commented
It has the edit screen details in there...

<img width="878" alt="Screenshot 2021-07-16 at 18 30 15" src="https://user-images.githubusercontent.com/9541/125979839-04a96a91-7f36-4979-9348-33868b747055.png">
<img width="713" alt="Screenshot 2021-07-16 at 18 30 46" src="https://user-images.githubusercontent.com/9541/125979844-2f5f2443-6810-4dfb-acd6-bd698f068e2a.png">

2021-07-16 16:32 UTC, illume approved these changes
👍 thanks

2021-07-20 11:47 UTC, merged