Allow other result success cases to complete the update
kinvolk/nebraska pull request #433
Opened 2021-08-04 17:48 UTC by joaquimrocha

We had a [limit](https://github.com/kinvolk/nebraska/blob/main/backend/pkg/api/events.go#L167) on how we consider an update to be done because we were only contemplating how Flatcar behaves.

Yet, as far as understand from the [protocol](https://github.com/google/omaha/blob/master/doc/ServerProtocolV3.md), there are [3 different ways](https://pkg.go.dev/github.com/kinvolk/go-omaha/omaha#EventResult) to represent success and we should definitely consider them.

Another issue with not understanding all success result cases is that when using the (deprecated but still useful) `updateservicectl`, the fake instances would reach an "unknown" state because of this [corner case logic](https://github.com/kinvolk/nebraska/blob/main/backend/pkg/api/events.go#L108).
With this PR it will successfully consider those fake instances updates to be completed, and I don't think the PR will change anything in the Flatcar case because we are [using only "ResultReboot" AFAICS](https://github.com/kinvolk/update_engine/blob/312ab260fce283e84635b73d92dd6d526d1e3d96/src/update_engine/omaha_request_action.cc#L136
). I'd like @pothos to double check this is the case.

2021-08-05 11:36 UTC, pothos commented
I've done some tests and it looked good but it's not easy to answer: there is an initialization in update-engine with `kTypeUpdateComplete` and `kResultSuccess` is the default - I don't know yet whether this is will be sent and under which conditions.

2021-08-05 11:53 UTC, pothos commented
Yes, so the instance sends `<event eventtype="3" eventresult="1"></event>` after the update payload is applied (showing in Nebraska logs as `event="update complete.success"`) and then after the instance rebooted it sends `<event eventtype="3" eventresult="2" previousversion="2….x.y"></event>` (showing in Nebraska as `event="update complete.success reboot"`).

2021-08-05 11:55 UTC, pothos requested changes

2021-08-05 11:55 UTC, pothos commented on backend/pkg/api/events.go
> +	if etype == EventUpdateComplete && (result == ResultSuccessReboot || result == ResultSuccess) {
```suggestion
	if etype == EventUpdateComplete && (result == ResultSuccessReboot || result == ResultSuccess) {
```
I would make it a property of the application whether `ResultSuccessReboot` or `ResultSuccess` is expected here.
Instead of adding a DB property you can also add a check here against the hardcoded Flatcar application ID.

2021-08-05 16:56 UTC, joaquimrocha commented on backend/pkg/api/events.go
> +	if etype == EventUpdateComplete && (result == ResultSuccessReboot || result == ResultSuccess) {
@pothos Did you mean to add a code suggestion?

So AFAIU, you're saying "keep this change you added but only if the app is not FCL".

2021-08-05 17:22 UTC, joaquimrocha commented
I have updated the branch to include the old FCL behavior and a test. We should start adding more tests, especially those covering special Flatcar behavior.

2021-08-06 11:36 UTC, pothos commented on backend/pkg/api/events.go
> +	if etype == EventUpdateComplete && (result == ResultSuccessReboot || result == ResultSuccess) {
Thanks, looks good now.

Yes, I didn't want to add a suggestion but just a comment on that line.

2021-08-06 11:37 UTC, pothos approved these changes

2021-08-06 13:51 UTC, merged