backend: Replace gin with oapi-codegen and echo
kinvolk/nebraska pull request #434
Opened 2021-08-09 10:38 UTC by yolossn

ToDo:

- [ ] Add Authorisation to spec.
- [ ] Fix Github Auth by changing login init logic in frontend (similar to OIDC).
- [ ] Finalize a Docs generation tool. [list of tools](https://openapi.tools/#documentation), [Option1](https://redocly.github.io/redoc/?url=https://raw.githubusercontent.com/kinvolk/nebraska/poc/backend/api/spec.yaml
)

2021-08-10 16:50 UTC, joaquimrocha commented
fixes #435

2021-08-12 10:27 UTC, yolossn commented on backend/pkg/handler/activity.go
> +func (h *Handler) PaginateActivity(ctx echo.Context, params codegen.PaginateActivityParams) error {
Replaces https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L946

2021-08-12 10:28 UTC, yolossn commented on backend/pkg/handler/app.go
> +func (h *Handler) PaginateApps(ctx echo.Context, params codegen.PaginateAppsParams) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L328

2021-08-12 10:28 UTC, yolossn commented on backend/pkg/handler/app.go
> +func (h *Handler) CreateApp(ctx echo.Context, params codegen.CreateAppParams) error {
Replaces:
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L203

2021-08-12 10:29 UTC, yolossn commented on backend/pkg/handler/app.go
> +func (h *Handler) GetApp(ctx echo.Context, appID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L301

2021-08-12 10:29 UTC, yolossn commented on backend/pkg/handler/app.go
> +func (h *Handler) UpdateApp(ctx echo.Context, appID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L236

2021-08-12 10:30 UTC, yolossn commented on backend/pkg/handler/app.go
> +func (h *Handler) DeleteApp(ctx echo.Context, appID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L277

2021-08-12 10:30 UTC, yolossn commented on backend/pkg/handler/channels.go
> +func (h *Handler) PaginateChannels(ctx echo.Context, appID string, params codegen.PaginateChannelsParams) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L672

2021-08-12 10:31 UTC, yolossn commented on backend/pkg/handler/channels.go
> +func (h *Handler) CreateChannel(ctx echo.Context, appID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L560

2021-08-12 10:32 UTC, yolossn commented on backend/pkg/handler/channels.go
> +func (h *Handler) UpdateChannel(ctx echo.Context, appID string, channelID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L591

2021-08-12 10:33 UTC, yolossn commented on backend/pkg/handler/groups.go
> +func (h *Handler) PaginateGroups(ctx echo.Context, appID string, params codegen.PaginateGroupsParams) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L464

2021-08-12 10:34 UTC, yolossn commented on backend/pkg/handler/groups.go
> +func (h *Handler) GetGroup(ctx echo.Context, appID string, groupID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L447

2021-08-12 10:34 UTC, yolossn commented on backend/pkg/handler/groups.go
> +func (h *Handler) UpdateGroup(ctx echo.Context, appID string, groupID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L382

2021-08-12 10:35 UTC, yolossn commented on backend/pkg/handler/groups.go
> +func (h *Handler) DeleteGroup(ctx echo.Context, appID string, groupID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L423

2021-08-12 10:36 UTC, yolossn commented on backend/pkg/handler/groups.go
> +func (h *Handler) GetGroupStatusTimeline(ctx echo.Context, appID string, groupID string, params codegen.GetGroupStatusTimelineParams) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L505

2021-08-12 10:37 UTC, yolossn commented on backend/pkg/handler/groups.go
> +func (h *Handler) GetGroupInstanceStats(ctx echo.Context, appID string, groupID string, params codegen.GetGroupInstanceStatsParams) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L522

2021-08-12 10:38 UTC, yolossn commented on backend/pkg/handler/groups.go
> +func (h *Handler) GetGroupVersionBreakdown(ctx echo.Context, appID string, groupID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L539

2021-08-12 10:38 UTC, yolossn commented on backend/pkg/handler/groups.go
> +func (h *Handler) GetGroupInstances(ctx echo.Context, appID string, groupID string, params codegen.GetGroupInstancesParams) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L851

2021-08-12 10:39 UTC, yolossn commented on backend/pkg/handler/groups.go
> +func (h *Handler) GetGroupInstancesCount(ctx echo.Context, appID string, groupID string, params codegen.GetGroupInstancesCountParams) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L877

2021-08-12 10:39 UTC, yolossn commented on backend/pkg/handler/instances.go
> +func (h *Handler) GetInstance(ctx echo.Context, appID string, groupID string, instanceID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L897

2021-08-12 10:40 UTC, yolossn commented on backend/pkg/handler/instances.go
> +func (h *Handler) GetInstanceStatusHistory(ctx echo.Context, appID string, groupID string, instanceID string, params codegen.GetInstanceStatusHistoryParams) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L831

2021-08-12 10:40 UTC, yolossn commented on backend/pkg/handler/instances.go
> +func (h *Handler) UpdateInstance(ctx echo.Context, instanceID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L911

2021-08-12 10:41 UTC, yolossn commented on backend/pkg/handler/omaha.go
> +func (h *Handler) Omaha(ctx echo.Context) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L980

2021-08-12 10:41 UTC, yolossn commented on backend/pkg/handler/packages.go
> +func (h *Handler) PaginatePackages(ctx echo.Context, appID string, params codegen.PaginatePackagesParams) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L808

2021-08-12 10:42 UTC, yolossn commented on backend/pkg/handler/packages.go
> +func (h *Handler) CreatePackage(ctx echo.Context, appID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L695

2021-08-12 10:42 UTC, yolossn commented on backend/pkg/handler/packages.go
> +func (h *Handler) GetPackage(ctx echo.Context, appID string, packageID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L791

2021-08-12 10:43 UTC, yolossn commented on backend/pkg/handler/packages.go
> +func (h *Handler) UpdatePackage(ctx echo.Context, appID string, packageID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L726

2021-08-12 10:44 UTC, yolossn commented on backend/pkg/handler/packages.go
> +func (h *Handler) DeletePackage(ctx echo.Context, appID string, packageID string) error {
Replaces
https://github.com/kinvolk/nebraska/blob/d625afd3e086d1223becf79c147360147b3ef97e/backend/cmd/nebraska/controller.go#L767

2021-08-16 13:39 UTC, joaquimrocha requested changes
These should be squashed with the places where they were introduced in this PR.

2021-08-16 13:39 UTC, joaquimrocha commented on frontend/src/js/stores/ApplicationsStore.ts
> +        this.applications = response.applications;
We shouldn't have to call methods with all parameters but intead receive the results as if the params had whatever default values, when they're omitted.

2021-08-16 13:39 UTC, joaquimrocha commented on frontend/src/js/utils/auth.ts
> +      }
Can you explain why this change is needed?

2021-08-16 13:39 UTC, joaquimrocha commented on frontend/src/js/components/Groups/EditDialog.tsx
> +      safeMode: false,
I think the backend should be resilient with those.

2021-08-16 13:40 UTC, joaquimrocha requested changes
Pressed submit too soon, but please squash the last commit with the place where it's introduced in the PR (if it was an error introduced there).

2021-08-16 13:46 UTC, joaquimrocha commented on backend/pkg/handler/app.go
> +func (h *Handler) PaginateApps(ctx echo.Context, params codegen.PaginateAppsParams) error {
Getting the apps count is very useful, but this is not atomic with the rest of the operation. So you can return a total num of apps that's different than the pagination reflects, and this can lead to issues that will be exposed to the user.
I wonder if we should perform the 2 operations atomically in api.getApps.

2021-08-16 13:54 UTC, yolossn commented on frontend/src/js/utils/auth.ts
> +      }
In OIDC auth flow, the frontend passes the `/login` as `login_redirect_url` param leading to an infinite loop.

2021-08-16 17:19 UTC, yolossn commented on backend/pkg/handler/app.go
> +func (h *Handler) PaginateApps(ctx echo.Context, params codegen.PaginateAppsParams) error {
AFAIK It is a standard practice to fetch the count and the data in two queries, also we cant fetch the count and data in the same query because we are paginating and the count result will always be 10 in that case. We follow this in the [GetInstances](https://github.com/kinvolk/nebraska/blob/348b30965727327c79c44e7eec6e7ff0079bd17f/backend/pkg/api/instances.go#L398) function too. Also, I think this is a rare case when a new application is created at the time taken to fetch the count. We can use a read-only transaction but it will block write operations like INSERT, UPDATE, DELETE, and COPY FROM, which can be costly [Refer](https://www.postgresql.org/docs/9.1/sql-set-transaction.html).

2021-08-16 17:22 UTC, yolossn commented on frontend/src/js/components/Groups/EditDialog.tsx
> +      safeMode: false,
If we can define which values are optional it will be easy to make the backend accept them. Previously it depended on falling back to default values of golang. Now since we are creating the models from the request it needs to be a bit more strict on which values are optional and which aren't.

2021-08-16 17:22 UTC, yolossn commented on frontend/src/js/stores/ApplicationsStore.ts
> +        this.applications = response.applications;
This makes more sense, Will make page and perpage optional 👍🏽

2021-08-19 14:25 UTC, merged