Add updater lib
kinvolk/nebraska pull request #460
Opened 2021-09-01 15:55 UTC by joaquimrocha

I am not entirely sure yet whether we'll keep this here or add it to the go-omaha package. It makes sense to go in the latter, but we need to test some specific behavior in nebraska with it, so for now let's do the PR against a non-main branch.

We also have a gazillion commits because they were initially added continuously to the proof-of-concept branch. I can squash them if needed.

- Add updater base code
- updater: Rename appVersion as instanceVersion and userId as instanceID
- updater: Move and rename the handler interface
- updater: Add UpdateInfo to wrap omaha.Response
- updater: Allow to test the current version from an env var
- updater: Add context to updateHandler functions
- updater: Set package name to updater
- updater: Fix module path
- updater: Abstract how omaha requests are performed
- updater: Add first tests
- updater: Fix New function to remove its dependency on retryablehttp
- updater: Add tests to omahaHandler
- updater: Don't let TryUpdate continue on error
- updater: Add initial docs
- updater: Don't include the URL in SendOmahaRequest
- updater: Test TryUpdate
- updater: Add setter/getter for instance version
- backend: Check for the manifest existence in UpdateInfo.GetVersion
- backend: Add UpdateInfo.GetPackage/s convenience methods

2021-09-01 17:31 UTC, invidian reviewed
Some thoughts. Overall code looks straightforward and good :+1: If some of my comments are against general style of the project, please ignore them :)

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +func NewTestHandler(a *api.API) *TestOmahaHandler {
Is it indented for test handler to be exported? Perhaps it should be moved to file without `_test.go` in name? It's unusual to export objects from test files as far as I know.

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +package updater
This could use a test package, so ensure we only do blackbox testing.
```suggestion
package updater_test
```

2021-09-01 17:31 UTC, invidian commented on updater/omahaHandler_test.go
> +package updater
Ditto blackbox testing.
```suggestion
package updater_test
```

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +	}
If it's a test handler, it could take `*testing.T` as an argument. Depends how it is intended to be used.

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +	omahaReqXML, err := xml.Marshal(req)
Also ditto Encoder.

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +		_ = os.Setenv("NEBRASKA_DB_URL", defaultTestDbURL)
If this fails, It's not good I guess :smile: 

Also, is it possible to avoid setting environment variable here? It's not very good for parallel testing, as those variables are global per process.

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +	assert.Equal(t, "updatefile.txt", pkg.Name)
Seems like a lot of asserts here. Should this be broken down into multiple subtests to give some proper names for those? It makes reading and running tests a lot easier.

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +	// Nothing to do
I saw other comments ending with `.` and it's a good practice, so it would be nice to be consistent.
```suggestion
	// Nothing to do.
```

Or even better, remove the comment :wink: IMO it does not add any valuable context.

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +	tGroup, err := a.AddGroup(&api.Group{Name: "group1", ApplicationID: tApp.ID, ChannelID: null.StringFrom(tChannel.ID), PolicyUpdatesEnabled: true, PolicySafeMode: false, PolicyPeriodInterval: "15 min
This setup code is duplicated, can it be moved to a helper function? It makes test more readable and also if there is some difference in test data, which is significant, it will be highlighted, which also makes test code more readable.

2021-09-01 17:31 UTC, invidian commented on updater/go.mod
> +	github.com/stretchr/testify v1.7.0
Given that this is new part of the project, do we want to depend on testify in general?

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +	tChannel, _ := a.AddChannel(&api.Channel{Name: "channel1", Color: "blue", ApplicationID: tApp.ID, PackageID: null.StringFrom(tPkg.ID), Arch: api.ArchAMD64})
If we always control input to `null.StringFrom`, does it make sense to pull it as a dependency? Or can this be actually `null` sometimes?

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +	})
IIRC one should not rely on fields order in struct, as it may silently break code when those are swapped (e.g. as part of memory-layout optimization).
```suggestion
	err = u.TryUpdate(context.TODO(), &updateTestHandler{
		applyUpdateResult: errors.New("something went wrong applying the update"),
	})
```

2021-09-01 17:31 UTC, invidian commented on updater/updater_test.go
> +	assert.Equal(t, oldVersion, u.instanceVersion)
To help with previous comment, this code could be broken down into test cases like:
- when applying update fails, tryUpdate 
  -  returns error to the user
  - does not bump instance version

2021-09-01 17:31 UTC, invidian commented on updater/updater.go
> +}
Should those method be exported? There is no test or example code for them.

2021-09-01 17:31 UTC, invidian commented on updater/omahaHandler.go
> +	resp, err := h.httpClient.Post(h.url, "text/xml", bytes.NewReader(requestByte))
If I do:
```go
f := &HttpOmahaReqHandler{}
f.Handle()
```

This will panic. perhaps `HttpOmahaReqHandler` should be unexported and `NewHttpOmahaReqHandler` should be returning an exported interface to take a defensive approach here?

2021-09-01 17:31 UTC, invidian commented on updater/handler.go
> +func NewEmptyHandler() UpdateHandler {
Do we want this to be exported?

2021-09-01 17:31 UTC, invidian commented on updater/updateInfo.go
> +func (u *UpdateInfo) GetVersion() string {
Seems all those could be helpers in `omaha.Response` struct, it would make things simpler.

2021-09-01 17:31 UTC, invidian commented on updater/doc.go
> +Package updater aims to simplify omaha-powered updates.
Should we have some license headers?

2021-09-02 09:26 UTC, joaquimrocha commented on updater/doc.go
> +reboot, then upon running the logic again and detecting that we're running a
Good point. @yolossn , please add ProgressUpdateCompleteAndRestarted instead of AndRebooted.

2021-09-02 09:28 UTC, joaquimrocha commented on updater/handler.go
> +	ApplyUpdate(ctx context.Context, info *UpdateInfo) error
I prefer to be more explicit here, since we're not sure if in the future we'll have Fetch/GetMetadata or something like that.

2021-09-02 09:32 UTC, joaquimrocha commented on updater/updateInfo.go
> +func (u *UpdateInfo) GetVersion() string {
I wanted to hide a bit omaha specific structs, and have a getter for the omaha.Response if a more advanced use needs to be done.

2021-09-02 09:35 UTC, invidian commented on updater/handler.go
> +	ApplyUpdate(ctx context.Context, info *UpdateInfo) error
Sure, sounds good. Marking as resolved.

2021-09-03 10:53 UTC, yolossn commented on updater/go.mod
> +	github.com/stretchr/testify v1.7.0
Any specific reason to not depend on testify? Or are you suggesting to use a better alternative?

2021-09-03 11:03 UTC, joaquimrocha commented on updater/updateInfo.go
> +}
The thing is that in most cases, at least when Nebraska is the server, we'll just have 1 URL, so this is just convenient IMO.

2021-09-03 11:12 UTC, invidian commented on updater/updateInfo.go
> +	if urls := u.GetURLs(); urls != nil {
GetURLs can still return empty slice if `len(app.UpdateCheck.URLs) == 0`, so line below will then panic.

2021-09-03 11:17 UTC, invidian commented on updater/updateInfo.go
> +}
I understand the convenience, but it seems to be that having a single function will make it more consistent (and possibly easier) for users to use, as there is no choice which one to use. Looking from usage perspective, the difference is the following:
```go
  if urls := getURLs(); len(urls) != 1 || urls[0] != "" {
    t.Log("all ok")
  }

  if url := getURL(); url != "" {
    t.Log("all good")
  }
```

I think having 2 very similar methods in API is more burden than changing `url != ""` to `len(urls) != 1 || urls[0] != ""`. Especially that this pattern repeats for other functions, which gets more highlighted when number of functions grows.

But I don't hardly insist on that as I don't have this much experience designing APIs like this.

2021-09-03 11:33 UTC, invidian commented on updater/go.mod
> +	github.com/stretchr/testify v1.7.0
I personally prefer to avoid pulling extra dependencies when possible to the project and with test frameworks, the thing is that you should use them consistently across entire project and if they get unmaintained for whatever reason, it's a lot of tedious work to replace them with something else.

I also often seen many misuses of `assert` vs `require` in tests, which causes misleading test errors and test suite panics, which I think makes it harder to develop etc. Example:
```go
  obj, err := c.New()
  assert.NoError(err) // require.NoError() should be used here, as usually when error is returned, object will be nil, so assert will produce a false-negative.
  assert.NotNil(obj)

  obj.Foo() // Even worse, test suite won't stop above and will panic on nil pointer dereference here.
```

I think Go standard `testing` package is good enough for most use cases and for example following `if err != nil` pattern in test code, you make it more familiar for reader, as opposed to "new concept of assert.X()" in test code. `testing` package is also less likely to be deprecated or having breaking changes and is more likely to be familiar for other Go developers. 

I also saw people tend to use a lot of `assert.X()`, without adding an annotation for it, which seems more usual with `t.Error()` or `t.Fatal` and I think adding this extra context why specific test is failing is very useful and allows to very quickly identify what goes wrong if used the right way, especially when you mix them together with BDD. To give an example:
```console
$ go test -run Test_Mutate/injects_sidecar_when/namespace_selector_matches ./internal/mutator/pod/agent/
time="2021-09-03T13:25:13+02:00" level=info msg="'infra-operator.newrelic.com/agent-injected' label value for Pod with no config selector: 'd881dff1cf97d45ecdfc8be347df2482bed2a557'"
--- FAIL: Test_Mutate (0.00s)
    --- FAIL: Test_Mutate/injects_sidecar_when (0.00s)
        --- FAIL: Test_Mutate/injects_sidecar_when/namespace_selector_matches (0.00s)
            injector_test.go:885: Mutating Pod: ensuring sidecar dependencies: ensuring Secret presence: creating secret test-namespace/:  "" is invalid: metadata.name: Required value: name is required
FAIL
FAIL    github.com/newrelic/newrelic-infra-operator/internal/mutator/pod/agent  0.010s
FAIL
```

There is no need to look at the code here to figure out what part of test is failing, as everything is provided.

On the other hand, if other Nebraska code already use it and you prefer to be consistent and you know how to make good use of it, I don't mind at all having it as a dependency. Just challenging you with question to make sure this is a deliberate decision, to avoid possible "accidental" problems in the future :)

I also know some people treat test frameworks almost as a religion, so I wanted to initially avoid going into this vs that discussion :smile:

2021-09-03 13:27 UTC, yolossn commented on updater/updater.go
> +}
This was intentional, It provides the user with the flexibility to send custom Omaha Requests. Will add tests and examples.

2021-09-06 10:58 UTC, yolossn commented on updater/updater.go
> +func New(omahaURL string, appID string, channel string, instanceID string, instanceVersion string) (*Updater, error) {
Sorry, I don't get the `remove NewWithOmahaRequestHandler completely,`. Do you mean to add OmahaRequestHandler also to the config struct?

2021-09-06 11:51 UTC, yolossn commented on updater/updater_test.go
> +	tChannel, _ := a.AddChannel(&api.Channel{Name: "channel1", Color: "blue", ApplicationID: tApp.ID, PackageID: null.StringFrom(tPkg.ID), Arch: api.ArchAMD64})
This is because the expected type is `null.String` and we can't use the string value though it is not null in these cases.

2021-09-06 12:05 UTC, joaquimrocha commented on updater/updater_test.go
> +	}
That's a good idea. This is a pattern that's been around in Nebraska/Coreroller for a while. Let's fix it in a another PR though.

2021-09-06 12:12 UTC, invidian commented on updater/updater.go
> +func New(omahaURL string, appID string, channel string, instanceID string, instanceVersion string) (*Updater, error) {
>Do you mean to add OmahaRequestHandler also to the config struct?

Yes, exactly. So then the contructor (`func New`) will initialize it when it's `nil`.

2021-09-06 14:24 UTC, yolossn commented on updater/doc.go
> +	u := updater.New("http://myupdateserver.io/v1/update", "io.phony.App", "stable", getInstanceID(), getCurrentVersion())
I am not sure if it is possible in this case as the example expects the Nebraska server to be running. Should we run the Nebraska backend in a goroutine to make this possible?

2021-09-06 14:26 UTC, yolossn commented on updater/go.mod
> +	github.com/stretchr/testify v1.7.0
Thanks, now I understand where you are coming from. I think we can stick with `testify` as it is used in Nebraska backend.

2021-09-06 14:41 UTC, yolossn commented on updater/updater.go
> +func (u *Updater) TryUpdate(ctx context.Context, handler UpdateHandler) error {
Only InstanceVersion value gets updated and I have added locks to the SetInstanceVersion and GetInstanceVersion functions. I think this should do, for now, we can add more checks if the scope increases.

2021-09-07 09:22 UTC, invidian commented on updater/doc.go
> +	u := updater.New("http://myupdateserver.io/v1/update", "io.phony.App", "stable", getInstanceID(), getCurrentVersion())
I guess it's fine if example returns an error by default? At least we make sure it does compile. It will also make code available to linters and formatters, which makes it easier to keep it consistent with other code.

2021-09-07 16:30 UTC, rata requested changes
Hi!

I've been looking at this, decided to center on the user-facing interface/docs first. I'll review code, tests and wording for comments later, after the first round of fixes (please ping me when done! :)). As the PR description doesn't guide me in any way in what way to review or what to pay attention to, I decided to do that. Let me know if you expected me to do something different! Also, no need to list the commits in the PR description if you are not going to mention anything about any commit in particular, github already lists them :)

Overall, it looks quite reasonable, keep up the good work!

I added several comments. Some are regarding what is exported by this pkg (IOW starts with a capital letter), I think there are lot of functions that should not be exported but that wasn't adjusted yet. To not create a lot of noise, I marked only some. Please review them all, I can look at it again in the next review if some has slipped out.

Documentation for exported types/functions is not present. Please add it, it is hard to review without that, I need to look at lot of details to guess it (I'm not familiar with omaha nor nebraska).

But here it goes a more general question about the whole interface: why not have only one pkg exported to the user? Let me elaborate, but bare in mind that, as some doc is missing, I might be doing wrong assumptions here.

But, why don't we want to just expose to the user one type that has the methods:
* New()
* CheckForUpdates()
* HasUpdate()
* GetVersion()
* ReportProgress()
* TryUpdate() --> not sure about this one, but we can leave for now

IMHO, this seems like a simpler interface to use, and doesn't mix together different things AFAIK. 

The `CheckForUpdates()` can cache the latest `info` (I mean the `UpdateInfo` type thing) in an non-exported field of the struct, getVersion() and HasUpdate() just check that `info` that is cached in the struct (and fail otherwise), and ReportProgress() can do what it does today, but then the user reports that it completed okay, it also does the `SetInstanceVersion()` as it now knows the version it was updated to (the `info` cached in the struct).

Note I have not added some other helpers (GetURLs(), etc.) that might be needed in my example, I didn't mean to compile that but just to communicate the gist of my thinking :). Also, the getters in go (as I mentioned in a comment) usually follow a different style, I didn't adapt those methods to that and probably many other things. I wanted this to be a simple to understand idea, not mix several changes in one :).

I think having ReportProgress() know the version it was worked on and automatically using SetInstanceVersion() internally is a nice usability improvement (don't get me wrong, I'm not saying it should be fixed this way, but I would like for thit to be improved in _some_ way). But, I don't know about omaha, let me know if I'm missing something.

2021-09-07 16:39 UTC, rata commented on updater/doc.go
> +the updates in order for it to be used:
Not sure if we need to mention this, though. Maybe we can just remove it? The New method takes a struct, that seems clear enough

2021-09-08 09:55 UTC, joaquimrocha commented
Hi @rata ,

Thanks for your review. I'd like to address your summary's comments here. We may reply to the in-code ones later.
Please find my reply chained below.

> [...] Also, no need to list the commits in the PR description if you are not going to mention anything about any commit in particular, github already lists them :)

FYI, the listing is done automatically by opening the PR with `gh` :shrug: 

> Overall, it looks quite reasonable, keep up the good work!

Thanks! But it's still WIP :slightly_smiling_face: 
 
> Documentation for exported types/functions is not present. Please add it, it is hard to review without that, I need to look at lot of details to guess it (I'm not familiar with omaha nor nebraska).

We added docs on how to use it. We quickly made the code available as a PR after interest from others, and it's also a good idea not to document all the methods when the signature/behavior may change, or we'd have to redo the API docs.
We should definitely have API docs once we're settled on the signatures.

> But here it goes a more general question about the whole interface: why not have only one pkg exported to the user? Let me elaborate, but bare in mind that, as some doc is missing, I might be doing wrong assumptions here.

One pkg as in a "nebraska package" instead of an "update" pkg? There are two reasons:
1. The Nebraska package and the updater aren't very much related. In fact, we have the updater lib in Nebraska ATM just for making it easier to test with Nebraska, but it makes sense to move the updater to go-omaha.
2. Even if it goes to go-omaha, this should be considered as a higher-level lib, thus making sense to keep as a different package from nebraska or go-omaha's main pkgs.

> But, why don't we want to just expose to the user one type that has the methods:
> 
> * New()
> * CheckForUpdates()
> * HasUpdate()
> * GetVersion()
> * ReportProgress()
> * TryUpdate() --> not sure about this on
e, but we can leave for now
> 
> IMHO, this seems like a simpler interface to use, and doesn't mix together different things AFAIK.

It does mix together different things :slightly_smiling_face: . The updater can be thought of as:
1. The configured machine/instance's data like instance id, instance version, etc.\
2. The available updates' information (has a new version, URL, packages, etc.).

Beyong knowing about the instance (in order to perform update checks and reports), the lib is stateless, so having information about the update (like "has update") in the updater itself is giving it a state which I am not sure is desired.

> The `CheckForUpdates()` can cache the latest `info` (I mean the `UpdateInfo` type thing) in an non-exported field of the struct, getVersion() and HasUpdate() just check that `info` that is cached in the struct (and fail otherwise), and ReportProgress() can do what it does today, but then the user reports that it completed okay, it also does the `SetInstanceVersion()` as it now knows the version it was updated to (the `info` cached in the struct).

Caching the latest update info looks like an early optimization based on a use-case that's not difficult to be implemented by the caller. IOW, it'd create an assumption that I am not sure is desired for everyone.

About setting the instance version automatically, maybe it does make sense to automatically update the instance version based on a given version number, but this is done in the Updater struct as that's the one holding the minimal state we have (the instance's info).

> Note I have not added some other helpers (GetURLs(), etc.) that might be needed in my example, I didn't mean to compile that but just to communicate the gist of my thinking :). Also, the getters in go (as I mentioned in a comment) usually follow a different style, I didn't adapt those methods to that and probably many other things. I wanted this to be a simple to understand idea, not mix several changes in one :).

Maybe we should use the exported variables in the struct (assuming that's the pattern), but that means we'd be duplicating data, and doesn't allow to have a "dynamic" getter. In any case, this is something we can definitely change later.

> I think having ReportProgress() know the version it was worked on and automatically using SetInstanceVersion() internally is a nice usability improvement (don't get me wrong, I'm not saying it should be fixed this way, but I would like for thit to be improved in _some_ way).

We could move the ReportProgress to the UpdateInfo struct or have it take an UpdateInfo, but I really want to avoid caching things based on an assumption that may have deep implications in how flexible the lib is.

Let me know if this makes sense.

2021-09-08 11:41 UTC, invidian reviewed
Some more comments :)

2021-09-08 11:41 UTC, invidian commented on updater/updater.go
> +		return nil, err
Errors should be annotated:
```suggestion
		return nil, fmt.Errorf("sending omaha request: %w", err)
```

2021-09-08 11:41 UTC, invidian commented on updater/updater.go
> +	return info, nil
```suggestion
	return NewUpdateInfo(resp, u.appID), nil
```

2021-09-08 11:41 UTC, invidian commented on updater/updater.go
> +		return err
```suggestion
		return fmt.Errorf("sending omaha request: %w", err)
```

2021-09-08 11:41 UTC, invidian commented on updater/updater.go
> +		return err
```suggestion
		return fmt.Errorf("checking for updates: %w", err)
```

2021-09-08 11:41 UTC, invidian commented on updater/updater.go
> +		return err
```suggestion
		return fmt.Errorf("fetching update: %w", err)
```

2021-09-08 11:41 UTC, invidian commented on updater/updater.go
> +			fmt.Println("error reporting ProgressError to omaha server:", progressErr)
Should this be printed only behind `u.debug`?

BTW, I think having some sort of logger here instead, with log levels would be better.

2021-09-08 11:41 UTC, invidian commented on updater/updater.go
> +		}
I wonder if it would make sense to have some helper function here for reporting progress, which could either accept given action or simply call it, so we can do here something like `return reportError(ctx, err)`

2021-09-08 11:41 UTC, invidian commented on updater/updater_test.go
> +	defer a.Close()
I think `t.Cleanup` should be used instead of `defer` here.

2021-09-08 11:41 UTC, invidian commented on updater/updater_test.go
> +	assert.False(t, info.HasUpdate)
Shouldn't this be `require.NoError`. Is `info` expected to be not nil when when error occurs?

2021-09-08 11:41 UTC, invidian commented on updater/updater_test.go
> +	newPkg, _ := a.AddPackage(&api.Package{Type: api.PkgTypeOther, URL: "http://sample.url/pkg", Version: "0.3.0", ApplicationID: appID, Arch: api.ArchAMD64, Filename: null.StringFrom("updatefile.txt")}
We should not be skipping error checking I believe.

2021-09-08 11:41 UTC, invidian commented on updater/updater_test.go
> +	a := newForTest(t)
I think either variable name or a function name should be improved here, as without looking at the definition, I have no clue what this function returns.

2021-09-08 11:41 UTC, invidian commented on updater/updater_test.go
> +func setup(t *testing.T, a *api.API, version string, policySafeMode bool, policyMaxUpdatesPerPeriod int) (string, string, *api.Channel) {
Maybe we can have some helper struct to name those parameters? I find current calls e.g. `setup(t, a, pkgVersion, false, 10)` quite ambiguous.

2021-09-08 12:30 UTC, joaquimrocha commented on updater/doc.go
> +update is being performed for one single instance of that application.
This makes the sentence simpler but I don't think it makes it clearer (on the contrary).

2021-09-08 12:33 UTC, joaquimrocha commented on updater/doc.go
> +  1. Check for an update, if there's one available then:
This is supposed to work with any omaha server, not just Nebraska.
We can add the `(if there is not, try again later)` part.

2021-09-08 12:35 UTC, joaquimrocha commented on updater/doc.go
> +report for that.
I think the paragraph is needed. The suggestion doesn't make things much clearer IMO.

2021-09-08 12:39 UTC, joaquimrocha commented on updater/doc.go
> +The caller is also responsible for keeping any local state the update
@yolossn , if you see a use of "us" when it should be "the caller", please use the latter. Caller is fine IMO and I found several examples using the term in the official go docs.

2021-09-08 12:42 UTC, joaquimrocha commented on updater/doc.go
> +progress reports automatically: TryUpdate
I think it is clear from the example it refers to. Maybe we allude that when we document the methods.

2021-09-08 12:56 UTC, joaquimrocha commented on updater/doc.go
> +	u.ReportProgress(ctx, updater.ProgressUpdateComplete)
Maybe we do need to revisit the progress report. We are very likely not sending the whole information in the event repot in omaha.
So maybe we need to use it as `updater.ReportProgress(ctx Context, info UpdateInfo, progress Progress)` in order to send more info in the report.

We could also set the instance version + report completion in the previous logic but one problem may be that the protocol has UpdateComplete and UpdateCompleteAndRebooted, and IIRC Flatcar may send Complete before sending CompleteAndRebooted, but it only sets the new version before reporting the latter.

So for the automatic setting, maybe we should have a new method `updater.CompleteUpdate(ctx Context, info UpdateInfo)` which sets the insance version & sends `UpdateComplete` (if you need a different behavior, like Flatcar does, just use the SetInstanceVersion + ReportProgress).

2021-09-08 12:56 UTC, joaquimrocha commented on updater/doc.go
> +	// If the update succeeded, then u.GetInstanceVersion() should be set to the new version
See my previous comments about why we're trying not to make too many assumptions.

2021-09-08 13:01 UTC, joaquimrocha commented on updater/doc.go
> +		setDownloadFile(ctx)
True. The idea was to illustrate how you may pass information you need for your update, from the FetchUpdate to the ApplyUpdate. But maybe changing the name to `setDownloadedFilePath` an extra comment like `// Set the downloaded file's path in the context, so we can use it in the ApplyUpdate`.

2021-09-08 13:05 UTC, joaquimrocha commented on updater/updater_test.go
> +	assert.False(t, info.HasUpdate)
You're right.

2021-09-08 13:07 UTC, joaquimrocha commented on updater/updater_test.go
> +	a := newForTest(t)
You're right. I copied it from other places in Nebraska which have been following this as a pattern as everything depends on having an API struct.
Let's name the var as api as you say.

2021-09-08 13:38 UTC, rata commented
@joaquimrocha 

> > Documentation for exported types/functions is not present. Please add it, it is hard to review without that, I need to look at lot of details to guess it (I'm not familiar with omaha nor nebraska).
> 
> We added docs on how to use it. We quickly made the code available as a PR after interest from others, and it's also a good idea not to document all the methods when the signature/behavior may change, or we'd have to redo the API docs.
> We should definitely have API docs once we're settled on the signatures.

Fair. I didn't know how of a WIP this was when posted that :)

> > Note I have not added some other helpers (GetURLs(), etc.) that might be needed in my example, I didn't mean to compile that but just to communicate the gist of my thinking :). Also, the getters in go (as I mentioned in a comment) usually follow a different style, I didn't adapt those methods to that and probably many other things. I wanted this to be a simple to understand idea, not mix several changes in one :).
> 
> Maybe we should use the exported variables in the struct (assuming that's the pattern)

No, it is not that. And what you supposed doesn't happen. But let's continue this in the appropriate review comment :)

> > I think having ReportProgress() know the version it was worked on and automatically using SetInstanceVersion() internally is a nice usability improvement (don't get me wrong, I'm not saying it should be fixed this way, but I would like for thit to be improved in _some_ way).
> 
> We could move the ReportProgress to the UpdateInfo struct or have it take an UpdateInfo, but I 

Sure, that works too.

> really want to avoid caching things based on an assumption that may have deep implications in how flexible the lib is.

Ok, I think this is the main thing: you want this to be more flexible than I thought. I tried to make it more simpler :)

> Let me know if this makes sense.

IMHO, both things make sense.

My "simpler to the extreme" proposal was just a more minimalistic updater, removing some boilerplate from users (like the `info` we pass around, we never want an older nor anything else than the last) to reduce the "cognitive load" on users, while still differentiate the two aspects you mentioned (number 1 from your list will be the config, number 2 is the questions you ask to know about the update that are methods).

Yours has more concepts and probably evolve better with the flexibility you want to have. As long as those usability issues are improved, both are fine for me as a user. Thanks!

2021-09-08 14:48 UTC, rata commented on updater/doc.go
> +	u.ReportProgress(ctx, updater.ProgressUpdateComplete)
`updater.CompleteUpdate(ctx, info)` LGTM. And probably document in the some other function to do this manually that `SetInstanceVersion()` is needed.

If flatcar sets Complete, then CompleteAndRebooted and the instance version is set just after CompleteAndRebooted, I wonder if nebraska considers an update was installed and is _running_ only after the CompleteAndRebooted. I mean, I wonder if _anything_ changes server-side when the CompleteAndRebooted is received that we might want to send it in any case.

But I don't know about Nebraska, maybe my worries don't make sense :)

2021-09-08 14:59 UTC, rata commented on updater/doc.go
> +		setDownloadFile(ctx)
Ohhh, I see what it is supposed to be now! I guess you mean the user should use [context.WithValue](https://pkg.go.dev/context#WithValue)?

Be aware that (from the docs):
> Users of WithValue should define their own types for keys

So, if the idea is to use this, we should advise to also create your own type... Which makes me wonder if it is really worth it for this simplified method for using the library.

What do you think?

2021-09-08 15:05 UTC, rata commented on updater/doc.go
> +  1. Check for an update, if there's one available then:
Ok. I still find the wording too fuzzy in the description. Is not clear which parts I need to do as an user of this library nor which parts the libraries does for me. To clarify that was my intent with "Use the library to ask _the omaha server_ ...".

2021-09-09 07:30 UTC, yolossn commented on updater/updater_test.go
> +		_ = os.Setenv("NEBRASKA_DB_URL", defaultTestDbURL)
Will fix in a separate PR. 
https://github.com/kinvolk/nebraska/pull/460/files#r702849460

2021-09-09 07:51 UTC, yolossn commented on updater/updater_test.go
> +	assert.Equal(t, "updatefile.txt", pkg.Name)
All the checks are for one test case.

2021-09-09 09:55 UTC, yolossn commented on updater/doc.go
> +		setDownloadFile(ctx)
The context can be used for other use cases also like using [context.WithTimeout](https://pkg.go.dev/context#WithTimeout) in case the download is taking too long for example. Also, the `setDownloadFile` and  `someFunctionThatDownloadsAFile` are just an example and not forcing the user to pass or not pass the context.

2021-09-09 09:59 UTC, yolossn commented on updater/doc.go
> +		download, err := someFunctionThatDownloadsAFile(info.GetURL())
`someFunctionThatDownloadsAFile` is just an example function and the user can choose to not pass or pass the context to the underlying functions.

2021-09-09 10:46 UTC, joaquimrocha commented on updater/doc.go
> +	u.ReportProgress(ctx, updater.ProgressUpdateComplete)
Nebraska special-cases Flatcar in a couple of occasions, one being the completion. So for all other apps, it considers Complete as meaning the whole update is finished.

2021-09-09 10:46 UTC, joaquimrocha commented on updater/omahaHandler.go
> +func NewDefaultOmahaRequestHandler(url string) OmahaRequestHandler {
Because you may manually create an instance of the Updater and use this as a the Omaha Request Handler?

2021-09-09 10:51 UTC, invidian commented on updater/omahaHandler.go
> +func NewDefaultOmahaRequestHandler(url string) OmahaRequestHandler {
@rata exported, unexported is Go terms :) https://tour.golang.org/basics/3

2021-09-09 13:23 UTC, yolossn commented on updater/omahaHandler.go
> +func NewHttpOmahaRequestHandler(url string, client *retryablehttp.Client) OmahaRequestHandler {
the `retryablehttp.Client` was preferred to implement the `OmahaRequestHandler` interface because there can be network errors that can break the call and the user will have to handle retries etc which can become a mess, something similar is used in the current `go-omaha` client ([Refer](https://github.com/kinvolk/go-omaha/blob/main/omaha/client/error.go#L44)). Since the `OmahaRequestHandler` interface is exported the user can use their own implementation of `OmahaRequestHandler`.

2021-09-09 13:27 UTC, invidian commented on updater/updater.go
> +type OmahaRequestHandler interface {
@rata this is an exported field on exported struct, hence it should (must?) be exported as well. Otherwise you can't know what type to put there.

>It was intentional as it provides the flexibility to the user to provide their own implementation of omahaHandler with a different http.Client. But now I am a bit confused if we have to use a transport as you mentioned here.

I think this is a good point. This interface allows to replace `Handle()` implementation, while replacing transport or http.Client allows to tinker with underlying bits of `Handle()` implementation.

It seems to be that both are actually useful from both testing and user perspective. Say, if you want to start talking let's say GRPC to Nebraska, you would use a custom handler.

However, if your Nebraska instance is behind a auth proxy, you want to use a custom http.Client (or transport) to inject authentication.

Having an interface for transport or http.Client also allows to use a mock client, so you can test the implementation, like erroring on bad response etc.

Having an alternative handler though, allows to test the updater easily, with test Nebraska responses.

2021-09-09 13:29 UTC, yolossn commented on updater/updateInfo.go
> +// GetVersion retuns the manifest version of the UpdateInfo.
We can simply not export `UpdateInfo` and make `NewUpdateInfo` the only way to create a `updateInfo`.

2021-09-10 07:48 UTC, invidian commented on updater/updateInfo.go
> +// GetVersion retuns the manifest version of the UpdateInfo.
@yolossn but returning an unexported type is an anti-pattern.

2021-09-10 07:50 UTC, invidian commented on updater/updateInfo.go
> +package updater
I dont' think it's common to use capital letters in file names in go. why not just `updateinfo.go`?

2021-09-10 10:50 UTC, yolossn commented on updater/omahaHandler.go
> +
I think this can be due to naming convention, should we opt for something like `omahaClient` and change the `Handle` function to `Do` ?

2021-09-10 10:51 UTC, yolossn commented on updater/omahaHandler.go
> +
I think this can be due to naming convention, should we opt for something like `omahaClient` and change the `Handle` function to `Do`? Ill also add documentation as required.

2021-09-10 11:06 UTC, joaquimrocha commented on updater/omahaHandler.go
> +
Sorry I was not clear enough with my reaction. I meant that we should document that the argument in TryUpdate is for the user to implement.
I don't think just because two things have Handler in their name, one has to implement the other. But if it's too confusing, then maybe renaming the `UpdateHandler` interface to `UpdateImpl` (implementation) or `UpdateInstaller` (which may hint it only applies, doesn't fetch, which is wrong). Unfortunately I cannot think of a better name right now.

2021-09-10 11:18 UTC, invidian commented on updater/omahaHandler.go
> +
Please no `Impl` in the interface name, it's a sign of bad naming. IMO `UpdateHandler` is not a very bad name and it's clearly distinguishable from `OmahaRequestHandler` (which does not handle updates, it handles Omaha requests).

@rata I think documentation + code examples would be very useful here to get an idea how things are suppose to work.

2021-09-10 12:14 UTC, rata commented on updater/doc.go
> +		setDownloadFile(ctx)
@yolossn Sure, but that is unrelated to what I'm saying, IIUC.

The user needs to implement the interface with `FetchUpdate()` and `ApplyUpdate()`. @joaquimrocha was saying the context there should be used to pass which file was downloaded and where. I'm pointing out that I'm not sure using the context for that is worth the effort, as you need to specify your own types.

Maybe the prototype of the interface should be different to allow a more light usage of the TryUpdate (that is the whole point of TryUpdate, in the end, more simplified usage). Maybe some things can be params to the ApplyUpdate(), instead of loading the context with that information...

2021-09-10 12:38 UTC, rata commented on updater/doc.go
> +progress reports automatically: TryUpdate
For me it was not clear, but :shrug: :)

2021-09-10 12:51 UTC, rata commented on updater/omahaHandler.go
> +
Yes, I guess documentation is enough. Just was confusing in the current state for me.

2021-09-10 12:56 UTC, rata commented on updater/doc.go
> +		download, err := someFunctionThatDownloadsAFile(info.GetURL())
sure, just that usually outgoing calls to servers should accept a Context, we do take a context and not use it as param in the example seems like it was overlooked. I'm ok if you think the example is better this way, for me it just looks weird.

2021-09-10 13:05 UTC, rata commented on updater/updateInfo.go
> +	if u.app == nil || u.app.UpdateCheck == nil || u.app.UpdateCheck.Manifest == nil {
If `UpdateInfo` doesn't use a pointer for app, we can slightly simplify this check. The other two, as they are in the omaha pkg, will remain.

This applies to other functions. AFAICS, we don't use the `nil` to easily know it was not initialized, so I guess it should simplify the code. But not completely convinced :)

2021-09-10 13:07 UTC, invidian commented on updater/doc.go
> +		download, err := someFunctionThatDownloadsAFile(info.GetURL())
Yeah, I'd pass it down to follow the convention. Otherwise perhaps we should rename `ctx` to `_` to "mark it" unused.

2021-09-10 13:10 UTC, rata commented on updater/updater.go
> +func NewAppRequest(u *Updater) *omaha.Request {
Yeap, good point, if it is nil this will probably have a not desired effect. Haven't looked into detail to make a clear proposal as you say, leave that to you and others :)

As a general thought, though: I think the code in this PR uses a lot pointers, maybe some stuff will be simpler if we just take the type instead of a pointer and make good use of the zero values. It seems it might be the case for several functions [here](https://github.com/kinvolk/nebraska/pull/460/files#r706164499), also here... I'm curious to see what happens if we try to remove pointers when we don't really need a pointer :)

2021-09-10 13:13 UTC, rata commented on updater/updater.go
> +type OmahaRequestHandler interface {
@yolossn oh, I see. 

@invidian I think it wil be nice if there is a dummy implementation that doesn't make requests, designed to allow users of this code to test the code they write using this library. Leaving the option to re-implement the method might be okay, but having the most common scenario (users being able to test their code) should be already be provided here IMHO.

I'll leave to others to decide when (can be ok to not do it as part of the PoC. Although I guess it is a very simple task, so maybe not worth leaving it out :))

2021-09-10 13:16 UTC, rata commented on updater/omahaHandler.go
> +
I think documentation is probably enough, yes. Just was confusing for me in the current WIP state :)

2021-09-10 13:46 UTC, rata commented on updater/omahaHandler.go
> +func NewHttpOmahaRequestHandler(url string, client *retryablehttp.Client) OmahaRequestHandler {
Thanks. And I guess we take the client, not the transport, for the other flexibility you mentioned [here](https://github.com/kinvolk/nebraska/pull/460#discussion_r705317894). I wonder if we can simplify this a little bit, but I probably won't have the time to follow the discussion, so I'm not going to try :)

2021-09-10 13:50 UTC, rata commented on updater/doc.go
> +	err := someFunctionThatExitsAndRerunsTheApp()
IMHO smells like something that can be improved.

2021-09-10 13:54 UTC, rata commented on updater/omahaHandler.go
> +	requestBuf := bytes.NewBuffer(nil)
It's simpler if we just use a linter instead of manual work from @invidian :-D

2021-09-10 14:07 UTC, joaquimrocha commented on updater/doc.go
> +		setDownloadFile(ctx)
I gave an example of sharing the state and why we may want to use the context there, but it was probably the worst example.
If users want to share the state between functions there are other ways, like using the struct where they implement the methods.

Regardless, passing the context guarantees we have a way in the future to inform the functions about e.g. a cancellation or timeout, so e.g. a download can be cancelled.

2021-09-10 14:22 UTC, joaquimrocha commented on updater/updateInfo.go
> +	if u.app == nil || u.app.UpdateCheck == nil || u.app.UpdateCheck.Manifest == nil {
I usually don't like to copy data (probably overcare from my C++ days), but in any case this is internal logic and I don't think it's so important as to make the code unreadable. So let's just keep it and try to move on.

2021-09-10 14:45 UTC, rata commented on updater/updateInfo.go
> +	if u.app == nil || u.app.UpdateCheck == nil || u.app.UpdateCheck.Manifest == nil {
Ok, if you prefer to keep it... Note the pointer issue is not limited to this, and there are several doubtious examples in the interfaces too (search for pointers in this page, after loading all the comments). And I didn't highlighted all the examples of pointers on the interfaces, that easily make the code buggy (not handling nil) or more complex (need to return an error now, in case it is nil, etc.).

IMHO, it is simpler to just clean it up of the uneeded pointers. But as you prefer, really :)

2021-09-10 17:46 UTC, yolossn commented on updater/updater.go
> +	}
If this is part of the Handler, it depends on the implementation of `OmahaRequestHandler` and the user might provide an implementation that doesn't support debug flag. Also, I think an additional marshal in debug mode is acceptable.

2021-09-10 18:07 UTC, yolossn commented on updater/updater.go
> +		}
We have to `reportError` the Omaha server and return the error received from `ApplyUpdate`. In the `return reportError(ctx,err)` case the error is only reported to the Omaha sever and the error from `ApplyUpdate` is not returned to the caller.

2021-09-10 19:54 UTC, yolossn commented on updater/updater.go
> +		omahaURL:        config.OmahaURL,
I would like the URL to be set in the updater as it reduces one less things to configure. So I will change the OmahaRequestHandler to take a URL param.

```go
type OmahaRequestHandler interface {
	Handle(url string, req *omaha.Request) (*omaha.Response, error)
}
```

2021-09-13 04:10 UTC, yolossn commented on updater/omahaHandler.go
> +func NewHttpOmahaRequestHandler(url string, client *retryablehttp.Client) OmahaRequestHandler {
I have used a `httpDo` interface like this to add context to the request.

```go
type HttpDo interface {
	Do(*http.Request) (*http.Response, error)
}
```

2021-09-13 04:22 UTC, yolossn commented on updater/updater.go
> +type OmahaRequestHandler interface {
I think I'll skip the dummy implementation for now. Will add it later.

2021-09-13 08:45 UTC, invidian reviewed
Overall, I like the direction this PR is going, the API is now much smaller, which it seems allow even more simplification (as stated in the comments).

2021-09-13 08:45 UTC, invidian commented on updater/updater.go
> +		return fmt.Errorf("no update available for app %v, channel %v: %v", u.appID, u.channel, info.UpdateStatus())
Should no update be treated as error? If so, perhaps it should be a typed error, so user can use `errors.Is()` to distinguish between no updates and failed update?

2021-09-13 08:45 UTC, invidian commented on updater/updater.go
> +			fmt.Println("reporting error to omaha server:", errors.Unwrap(reportErr))
I believe user-printed messages should be capitalized.
```suggestion
			fmt.Println("Reporting error to omaha server:", errors.Unwrap(reportErr))
```

2021-09-13 08:45 UTC, invidian commented on updater/updater.go
> +	if err != nil {
To be consistent with other statements.
```suggestion
	if err := u.ReportProgress(ctx, ProgressDownloadFinished); err != nil {
```

2021-09-13 08:45 UTC, invidian commented on updater/updater_test.go
> +	assert.Error(t, err)
That should be 2 different test cases.

2021-09-13 08:45 UTC, invidian commented on updater/updater_test.go
> +	newPkg, err := apiInstance.AddPackage(&api.Package{Type: api.PkgTypeOther, URL: "http://sample.url/pkg", Version: "0.3.0", ApplicationID: appID, Arch: api.ArchAMD64, Filename: null.StringFrom("updat
Can we re-format to avoid such long lines? They are difficult to read.

2021-09-13 08:45 UTC, invidian commented on updater/updater_test.go
> +	assert.Equal(t, "updatefile.txt", pkg.Name)
With update info as a struct, this tests will also become much simpler.

2021-09-13 08:45 UTC, invidian commented on updater/updater_test.go
> +			applyUpdateResult: nil,
We should also test that error has been reported when error occurs, right?

2021-09-13 08:45 UTC, invidian commented on updater/updater_test.go
> +		},
I think this should be a separate test, with asserts on what's the expected outcome of successful update. In this case, I think it's:
- version has been updated
- success has been reported

We could also use a more descriptive language for test cases, so they become a list of properties of the package. See https://youtu.be/rIKDO7c8kKI?t=2764 as a good example.

In our case, we could have:
```go
func Test_TryUpdate(t *testing.t) {
  t.Run("returns_error_when", func(t *testing.T) {
    ...
  })

  t.Run("when_succeeds_marks_update_as_complete", func(t *testing.T) {
    // Here we should check at least one side-effect of CompleteUpdate(), to make sure it got called.
    // All side-effects of CompleteUpdate() should possibly be tested separately.
    //
    // Alternatively, we could test here, that when TryUpdate() succeeds,
    // calling it again returns a NoUpdateAvailable error.
  })
}
```

2021-09-13 08:45 UTC, invidian commented on updater/updater_test.go
> +func ExampleUpdater() error {
Can we move example file separate from unit tests? e.g. `updater_examples_test.go`? I think this will make it easier to find and read.

2021-09-13 08:45 UTC, invidian commented on updater/updater_test.go
> +		return err
I'd wrap errors as well here, to promote good patterns :)

2021-09-13 08:45 UTC, invidian commented on updater/doc.go
> +
Now that we have examples, can this be removed from documentation?

2021-09-13 08:45 UTC, invidian commented on updater/omahahandler.go
> +package updater
`omahahandler.go`, hehe, or, "haha" :smile:

2021-09-13 08:45 UTC, invidian commented on updater/omahahandler.go
> +type HTTPDo interface {
Maybe `HTTPDoer`? https://www.0value.com/let-the-doer-do-it

2021-09-13 09:26 UTC, rata commented on updater/doc.go
> +		setDownloadFile(ctx)
Yeap, those seem way like a way better alternative. I think the example can be improved with that (whenever you feel confident the API won't change and want to do this), and probably stop taking the context param in `SetDownloadFile()`, as that is super confusing at least for me.

2021-09-13 10:23 UTC, yolossn commented on updater/updater.go
> +	app.AddUpdateCheck()
No, the `newAppRequest` creates an app request using the `appID` configured in the updater and the same `appID` is used in `GetApp`. Also, I think you might have confused `GetApp` as a `UpdateInfo` function but it is `*omaha.Request` function provided by the `go-omaha` library.

2021-09-13 10:26 UTC, yolossn commented on updater/updater.go
> +	app.AddUpdateCheck()
No, the `newAppRequest` creates an app request using the `appID` configured in the updater and the same `appID` is used in `GetApp`, so `GetApp` doesn't return nil in this case.

2021-09-13 10:35 UTC, joaquimrocha commented on updater/doc.go
> +  1. Check for an update, if there's one available then:
This paragraph is not supposed to tell you which parts are done by the caller or the lib, this is supposed to describe in a very high-level the basic approach of performing an update. It's deliberately simplistic because that's the most basic concept we want the reader to grasp, before going into details (which the example should convey).

2021-09-13 10:52 UTC, joaquimrocha commented on updater/doc.go
> +	func getAppVersion() string {
This is the version the machine has, or the version of the OS/app/system that's currently installed, which will be used for asking the server for an update. So I think it's better to keep the `getCurrentVersion` name.

2021-09-13 10:52 UTC, joaquimrocha commented on updater/doc.go
> +  1. Check for an update, if there's one available then. if there is not, try again later.
Use a capital `If`

2021-09-13 10:52 UTC, joaquimrocha commented on updater/doc.go
> +		// let's install the update!
Use capital `// Let's` just for consistency.

2021-09-13 10:52 UTC, joaquimrocha commented on updater/doc.go
> +		// This should be users own implementation
```suggestion
		// This should be the caller's own implementation.
```

2021-09-13 10:52 UTC, joaquimrocha commented on updater/doc.go
> +		// Your own implementation here...
Let's keep the person used before:
```suggestion
		// The caller's own implementation here...
```

And below as well

2021-09-13 10:52 UTC, joaquimrocha commented on updater/doc.go
> +		// Your own implementation here...
```suggestion
		// The caller's own implementation here...
```

2021-09-13 10:52 UTC, joaquimrocha commented on updater/updateinfo.go
> +// GetVersion returns the manifest version of the UpdateInfo,
This and other methods still say `Get..`

2021-09-13 10:52 UTC, joaquimrocha commented on updater/updater.go
> +		return fmt.Errorf("no update available for app %v, channel %v: %v", u.appID, u.channel, info.UpdateStatus())
This was something I thought about initially. But for me, the concept of getting an error when there's no update available can be misleading. And having to check use `errors.Is` for understanding whether there's an error is a bit less readable than having `info.HasUpdate()` IMO.

Looking at it again, if we are not doing anything  with the struct when there's no update available (besides checking if there's an update), maybe it's more "goist" to do what you're saying.

@yolossn , WDYT?

2021-09-13 10:52 UTC, joaquimrocha commented on updater/updater_test.go
> +	newPkg, err := apiInstance.AddPackage(&api.Package{Type: api.PkgTypeOther, URL: "http://sample.url/pkg", Version: "0.3.0", ApplicationID: appID, Arch: api.ArchAMD64, Filename: null.StringFrom("updat
We should apply some formatter. That can come in the end.

2021-09-13 11:17 UTC, yolossn commented on updater/updater.go
> +		return fmt.Errorf("no update available for app %v, channel %v: %v", u.appID, u.channel, info.UpdateStatus())
Since the `TryUpdate` function tries to automatically checks and applies the `UpdateHandler` functions, If an error is not returned for this the user will not know the difference between successfully update being applied and skipping the steps as no update is available. Note that the `UpdateInfo` is not available to the user to check `info.HasUpdate()`.

Also, the goal of `TryUpdate` is to abstract as much Omaha-specific knowledge as possible, I prefer returning a typed error.

2021-09-13 11:17 UTC, yolossn commented on updater/doc.go
> +
@joaquimrocha  thoughts ?

2021-09-13 11:18 UTC, yolossn commented on updater/doc.go
> +	func getCurrentVersion() string {
Refer: https://github.com/kinvolk/nebraska/pull/460#discussion_r707212261

2021-09-13 11:21 UTC, yolossn commented on updater/updateinfo.go
> +	OmahaResponse() omaha.Response
@joaquimrocha  thoughts ?

2021-09-13 11:21 UTC, yolossn commented on updater/updater.go
> +}
@joaquimrocha  thoughts?

2021-09-13 12:15 UTC, invidian commented on updater/updater.go
> +var NoUpdateError = errors.New("no update available for app")
Better use const rather than globally writeable variable, as anyone can overwrite this one.
```go
type NoUpdateError struct{}

func (e NoUpdateError) Error() string {
  return "no update available for app"
}
```

2021-09-13 13:01 UTC, joaquimrocha commented on updater/doc.go
> +
Makes sense.

2021-09-13 13:21 UTC, joaquimrocha commented on updater/updater.go
> +}
Is this a pattern that's common in Go?
I imagine myself using an `Updater` instance I initialize with `New`, and calling methods on it. If one method requires updating it and others don't, that's IMO more complicated to maintain.

Also, if we're never changing the struct than we might as well not have setters, and just always create instances on change. So I think I prefer to keep this minimal state which is the machine info.

2021-09-13 13:44 UTC, joaquimrocha commented on updater/updateinfo.go
> +	OmahaResponse() omaha.Response
I don't love having to duplicate the data around, but let's go with the convention Mateusz is suggesting.
All of the getters here should be fields, except for the `URL()` which I really don't want to have as a duplicate of the first element of `URLs`, and `Package()` for consistency with the `URL()` (even though Packages are pointers).

2021-09-13 13:49 UTC, invidian commented on updater/updater.go
> +}
It's not a very common pattern as far as I know, but I sure see some benefits for it. But now that I think about it, after returning new instance, we would have to do something with old instance as well, to make it not make an update twice, so I guess current approach is good.

I'll mark it as resolved.

2021-09-13 13:49 UTC, joaquimrocha commented on updater/updater_example_test.go
> +
BTW, @invidian , I remembered an important part of why we didn't use an error in the `CheckForUpdates` when there is no update: we still get an `OmahaResponse` from it, and that may be useful for some use cases.
So either we don't export at all the OmahaResponse in the UpdateInfo (and return an error if no update is there, meaning no `HasUpdate` method is needed), or we keep the OmahaResponse and we don't return an error.

2021-09-13 13:54 UTC, invidian commented on updater/updater_example_test.go
> +
Hmm, but how does `TryUpdate` allows exposing the `OmahaResponse` right now? I don't see a way right now?

We could also make this behavior configurable for the user?

2021-09-13 14:33 UTC, joaquimrocha commented on updater/updater_example_test.go
> +
`TryUpdate` is a high-level way of performing the updates, so no `OmahaResponse` is expected to be used there.
Still, `TryUpdate` passes the `UpdateInfo` struct to each method, so the methods could actually get the omaha response, it's just not expected that they need to.

2021-09-13 14:37 UTC, invidian commented on updater/updater_example_test.go
> +
But what is wrong with the existing implementation? IMO it's fine that TryUpdate returns an error on no updates (as, it attempts to do an update), while CheckForUpdates don't need to.

2021-09-13 14:39 UTC, joaquimrocha commented on updater/updater_example_test.go
> +
I think my initial message was because you or Rodrigo said that CheckForUpdates could return an error when no update was available.

2021-09-14 17:50 UTC, invidian commented
Yes, I'd like to review it again, I'll try to do it by tomorrow.

2021-09-15 10:47 UTC, invidian commented
I'm looking into it right now, but it seems some commits slipped in here related to frontend and backend. Are they needed here?

2021-09-15 11:12 UTC, joaquimrocha commented
> I'm looking into it right now, but it seems some commits slipped in here related to frontend and backend. Are they needed here?

That's because I likely didn't update the target branch. Give me 1 min.

2021-09-15 11:15 UTC, joaquimrocha commented
@invidian I don't know what's going on with Github because it should be showing on the new commits on top of updater.
Please review from the "Add updater base code" commit up.

2021-09-15 11:17 UTC, invidian commented
@joaquimrocha perhaps some branch need a rebase?

2021-09-15 11:18 UTC, rata commented
@joaquimrocha thanks!

I think I hit this github issue before. If you go to the top of this page, click edit, then switch the base branch to something else and save (the commits will not be what you want), but then if you do the same but with th branch that it is now, it will show the proper commits in the PR

2021-09-15 11:23 UTC, joaquimrocha commented
> @joaquimrocha perhaps some branch need a rebase?

I had rebased it, but it does look like a bug, as Rodrigo mentioned.

2021-09-15 13:39 UTC, invidian reviewed
Overall looks very good, I pointed some nits mainly, as the exported API looks really clear now, seems like an easy thing to use, which is very cool!

I'm a bit concerned about the tests though, some cases are missing + large portion of the tests require a database which is considered a red flag, as databases tends to be slow. I think it would be much better if we could mock the responses, so we can to thorough testing, then have some small integration tests actually using the database. If can even be the same test suite, just using different Omaha handler, just one run as unit tests and another one as integration test.

As I don't have a database running right now, I cannot assert how good the coverage is on the updater.

2021-09-15 13:39 UTC, invidian commented on updater/updateinfo_test.go
> +			}
Rather than so many asserts, I think we can now use `reflect.DeepEqual` or `cmp.Diff` to make it easier and more readable.

2021-09-15 13:39 UTC, invidian commented on updater/updater.go
> +// and set the current instance version of the updater.
This right now is very hard to read when rendered. Can we document each interface method next to definition rather than all in top level comment?

![Selection_469](https://user-images.githubusercontent.com/16539896/133440323-3a20459a-7505-4c9f-ad57-84080fe3e131.png)

2021-09-15 13:39 UTC, invidian commented on updater/updater.go
> +	updater.omahaReqHandler = config.OmahaReqHandler
I guess that should be fine?
```suggestion
		debug:           config.Debug,
		omahaReqHandler: config.OmahaReqHandler
	}
```

2021-09-15 13:39 UTC, invidian commented on updater/updater.go
> +// newAppRequest create an omaha request containing
```suggestion
// newAppRequest create an Omaha request containing
```

2021-09-15 13:39 UTC, invidian commented on updater/updater.go
> +// to the omaha server.
```suggestion
// CheckForUpdates sends a request to the Omaha server checking if the application has any new updates.
// .
```

2021-09-15 13:39 UTC, invidian commented on updater/updater.go
> +		return nil, fmt.Errorf("sending update check omaha request:%w", err)
```suggestion
		return nil, fmt.Errorf("sending update check omaha request: %w", err)
```

2021-09-15 13:39 UTC, invidian commented on updater/updater.go
> +	return nil
Seems this part of code could be put in a helper to deduplicate code from `ReportError`.

2021-09-15 13:39 UTC, invidian commented on updater/updater.go
> +// the optional errorCode can be used to send custom
```suggestion
// that an error occured during the installation process.
// The optional errorCode can be used to send custom
```

2021-09-15 13:39 UTC, invidian commented on updater/updater.go
> +// SendOmahaRequest sends the event request to the omaha server
```suggestion
// SendOmahaEvent sends the event request to the Omaha server
```

2021-09-15 13:39 UTC, invidian commented on updater/updater.go
> +	return u.SendOmahaRequest(ctx, req)
We could perhaps decorate the error here.

2021-09-15 13:39 UTC, invidian commented on updater/updater.go
> +		return fmt.Errorf("%w %v, channel %v: %v", NoUpdateError{}, u.appID, u.channel, info.UpdateStatus)
Maybe we can make those fields a struct field, so they are easily accessible by the client? It seems like a lot of formatting here.
```suggestion
		return NoUpdateError{
		  AppID: u.appID,
		  Channel: u.channel,
		  UpdateStateus: info.UpdateStatus,
		}
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_example_test.go
> +	// download file logic goes here
```suggestion
	// Download file logic goes here.
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_example_test.go
> +	// extract and install update logic goes here
```suggestion
	// Extract and install update logic goes here.
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_example_test.go
> +		return fmt.Errorf("error checking updates for app: %s, err: %w", conf.AppID, err)
This should be more idiomatic:
```suggestion
		return fmt.Errorf("checking updates for app %q: %w", conf.AppID, err)
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_example_test.go
> +		// Oops something went wrong
```suggestion
		// Oops something went wrong.
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_example_test.go
> +		return err
```suggestion
		return fmt.Errorf("downloading update: %w", err)
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_example_test.go
> +	// The download was successful, let's inform that to the omaha server
```suggestion
	// The download was successful, let's inform that to the Omaha server.
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_example_test.go
> +	// This should be your own implementation
```suggestion
	// This should be your own implementation.
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_example_test.go
> +		// Oops something went wrong
```suggestion
		// Oops something went wrong.
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_example_test.go
> +		return err
```suggestion
		return fmt.Errorf("applying update: %w", err)
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_example_with_update_handler_test.go
> +	}
Maybe it's worth showing here an example of NoUpdateError handling?

2021-09-15 13:39 UTC, invidian commented on updater/updater_test.go
> +	"github.com/kinvolk/nebraska/backend/pkg/omaha"
I guess that should go together as it's a separate Go module?
```suggestion
	"github.com/stretchr/testify/require"
	"gopkg.in/guregu/null.v4"
	"github.com/kinvolk/nebraska/backend/pkg/api"
	"github.com/kinvolk/nebraska/backend/pkg/omaha"
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_test.go
> +	if _, ok := os.LookupEnv("NEBRASKA_DB_URL"); !ok {
Because this tests are not skipped, I'm not even able to see the test coverage in IDE unless I modify the test to skip it :disappointed: 

Also, it seems that a big part of updater code is not covered by unit tests, which is also not very good :/ Can we perhaps use mock for `OmahaRequestHandler` instead of requiring a database/nebraska to be running?

2021-09-15 13:39 UTC, invidian commented on updater/updater_test.go
> +		assert.Error(t, err)
I think we should require error + assert nil here, otherwise 2nd check will be a false positive.

2021-09-15 13:39 UTC, invidian commented on updater/updater_test.go
> +	assert.Equal(t, expected.Packages, info.Packages)
Can we use `reflect.DeepEqual` here for simplicity? Or maybe assert library already provides some helper for it?

2021-09-15 13:39 UTC, invidian commented on updater/updater_test.go
> +		// check if version is changed in
```suggestion
		// Check if version is changed in.
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_test.go
> +		// check if no new update is available for instance.
```suggestion
		// Check if no new update is available for instance.
```

2021-09-15 13:39 UTC, invidian commented on updater/updater_test.go
> +	})
Seems like this should be 2 subtests, one for checking instance version, another one for testing that there is no further updates available. Just wrapping with `t.Run()` with right names should be sufficient :)

2021-09-15 16:46 UTC, joaquimrocha commented
> Overall looks very good, I pointed some nits mainly, as the exported API looks really clear now, seems like an easy thing to use, which is very cool!
> 
> I'm a bit concerned about the tests though, some cases are missing + large portion of the tests require a database which is considered a red flag, as databases tends to be slow. I think it would be much better if we could mock the responses, so we can to thorough testing, then have some small integration tests actually using the database. If can even be the same test suite, just using different Omaha handler, just one run as unit tests and another one as integration test.
> 
> As I don't have a database running right now, I cannot assert how good the coverage is on the updater.

We're actually thinking of moving the updater completely to the go-omaha project now that it's reviewed. The reason why we kept it here in the beginning was to really make sure we could easily test it with Nebraska as a backend. If we keep some of this testing here, we run the tests in CI as we already do for the backend.

2021-09-15 16:50 UTC, joaquimrocha commented on updater/omahahandler.go
> +func (h *httpOmahaReqHandler) Handle(ctx context.Context, url string, req *omaha.Request) (*omaha.Response, error) {
Not really (several Nebraska servers) but I the Handle implementation is the important thing here, and I think it makes sense to stress that by passing the URL directly (also allows us to use different URLs in the future, if e.g. we have an endpoint for a graph of versions).

2021-09-15 16:59 UTC, joaquimrocha commented on updater/updater_test.go
> +	})
Now, this is about what's expected when trying to update twice in a row.

2021-09-15 17:01 UTC, joaquimrocha commented on updater/updater_test.go
> +	assert.Equal(t, expected.Packages, info.Packages)
The omaha response would differ. Let's keep this.

2021-09-16 11:12 UTC, joaquimrocha commented on updater/omahahandler_test.go
> +	go s.Serve()
Let's address at a later point since this is in tests anyway.

2021-09-16 11:13 UTC, merged

2021-09-16 11:13 UTC, joaquimrocha commented
Thank you @rata and @invidian for your thorough reviews. And @yolossn for enduring them :slightly_smiling_face: 
Team work! :mechanical_arm:

2021-09-16 11:30 UTC, invidian commented
@joaquimrocha there seems to be a lot of unresolved conversations still. Do we plan to address them somehow?

2021-09-16 11:43 UTC, joaquimrocha commented on updater/updater_test.go
> +		return err
This has been done but not resolved.

2021-09-16 11:44 UTC, joaquimrocha commented on updater/updater_test.go
> +func ExampleUpdater() error {
This has been done too.

2021-09-16 11:49 UTC, joaquimrocha commented on updater/updater.go
> +}
There's locking now. Resolving.

2021-09-16 11:51 UTC, joaquimrocha commented on updater/updater.go
> +	fmt.Println("Version before run:", u.instanceVersion)
No longer present.

2021-09-16 11:52 UTC, joaquimrocha commented on updater/updater_test.go
> +package updater
We access one not exported method, so I moved it back to whitebox testing. I made the mistake of having the example be part of the packge too, so I will revert that one later.

2021-09-16 11:54 UTC, joaquimrocha commented on updater/doc.go
> +Package updater aims to simplify omaha-powered updates.
That's not needed acording to a recent internal message.

2021-09-16 12:45 UTC, joaquimrocha commented
I think @yolossn addressed most of the comments, although some remained unresolved. I have resolved a few already but need to focus on something else.
Maybe when @yolossn is back next week he can verify if we have some unaddressed comments and we can do those in a new PR if needed.

2021-09-20 12:36 UTC, yolossn commented on updater/updateinfo.go
> +	omahaResponse *omaha.Response
We don't want to let the user update the value, so didn't expose the value and added a getter for the same.

2021-09-20 12:44 UTC, invidian commented on updater/updateinfo.go
> +	omahaResponse *omaha.Response
This struct does not carry any functionality except getters, so what's the point of not allowing user to set it?

Moreover, if user plans to create a mock of `Updater` interface for testing and their update code use Omaha response, they won't be able to provide a mocked data.