backend: Allow Config to be set both from env and flag
kinvolk/nebraska pull request #468
Opened 2021-09-08 12:20 UTC by yolossn

This patch allows the user to use both env and flags to
configure the nebraska server. Note that the flag
overrides the env.

Signed-off-by: Santhosh Nagaraj S <santhosh@kinvolk.io>

2021-09-08 15:17 UTC, joaquimrocha approved these changes
Assuming this is retro-compatible with the flags we use on `main`, and that the use of one flag doesn't invalidate any used env variables (just simply overrides the corresponding env var), it LGTM.

2021-09-08 15:17 UTC, joaquimrocha commented on backend/pkg/api/channels.go
> -func (api *API) getSpecificChannels(channelID ...string) ([]*Channel, error) {
This commit was also in the product-id PR, so we should remove it AFAIU.

2021-09-10 15:20 UTC, joaquimrocha requested changes
I have tried again and the env vars don't seem to be working.
BTW, I have also just realized that, unless I am confused, the config seems be exported as a package, but I am not sure we want this because config seems very intimate to running nebraska, not something that may be used by other modules IMO.

2021-09-10 20:06 UTC, yolossn commented
The code stopped working as expected once I changed from `spf13/pflag` provider to golang standard `flag` to support flags with single `-`. I'll investigate if there are any other ways to handle both cases. 

The `config` package is exported because the `handler` package which is exported is dependent on it. Making `config` internal makes `handler` unusable from any external code.

2021-09-15 13:14 UTC, joaquimrocha approved these changes

2021-09-15 13:20 UTC, joaquimrocha approved these changes

2021-09-15 13:20 UTC, merged