chore: Split frontend and backend build parts
kinvolk/nebraska pull request #503
Opened 2021-10-26 10:41 UTC by guilhem

# Split frontend and backend build parts

## Makefile

- `make` will call `Makefile` in _frontend_ and _backend_
- `make run` call `run` in both _frontend_ and _backend_

## Dockerfile

- use _distroless_ for run
  - use non-root user
- make binary static
  - and make it smaller
- use _node_ image for frontend build
- use caching
  - remove `non-cache` build parameter
  - improve `.dockerignore`
  - use docker/dockerfile:1.3 syntax for better caching

2021-11-04 10:34 UTC, joaquimrocha requested changes
@guilhem Thanks for another nice set of changes. I left some comments.

2021-11-04 10:34 UTC, joaquimrocha commented on .github/workflows/build-container.yml
> +
Is this needed because of the changes to how the image is built? If that's the case then maybe the changes should be squashed together.

2021-11-04 10:34 UTC, joaquimrocha commented on .github/workflows/backend.yml
> -      uses: actions/checkout@v1
Commenting here but it's for the whole patch: these changes are a good improvement, both the splitting & the overall improvements.
Since they have more than just moving things around, it's more difficult to review and catch any potential issues, but I know splitting the commit like that now is even a bigger chore.

I would like though to keep the old targets for compatibility (we are calling these from scripts and may have users doing so as well).

@guilhem , do you think you can do these updates?

2021-11-04 11:21 UTC, guilhem commented on .github/workflows/backend.yml
> -      uses: actions/checkout@v1
Yes, splitting van be challenging, but I can try :)

I tried to keep compatibility by forwarding target to nested Makefile... unsuccessfully.
But I can modify old targets for compatibility.

2021-11-04 11:23 UTC, guilhem commented on .github/workflows/build-container.yml
> +
"Set up QEMU" is not necessary.
It's here if we want to do multi arch (cross arch building).

2021-11-15 00:05 UTC, guilhem commented on .github/workflows/backend.yml
> -      uses: actions/checkout@v1
@joaquimrocha in some way I spited commits.
It may be better, but let me know.

2021-11-15 17:15 UTC, joaquimrocha requested changes
Thanks for the changes @guilhem !
I left a couple of small comments. I also ran the image build command, both locally with podman and in a Github workflow, and I am getting an issue when mounting the cache:

Respectively:
```
Error: error building at STEP "RUN --mount=type=cache,target=$GOPATH/pkg/mod make build": error resolving mountpoints for container "99a4f2744073233ac657940770d935f669a8c03e8f55df3178c6d7a98d560d51": invalid filesystem type "cache"
make: *** [Makefile:109: image] Error 125
```

```
RUN --mount=type=cache,target=$GOPATH/pkg/mod 	make build
the --mount option requires BuildKit. Refer to https://docs.docker.com/go/buildkit/ to learn how to build images with BuildKit enabled
make: *** [Makefile:109: image] Error 1

Problem making Nebraska base image!
```

Maybe it's a good idea to split out the image build changes to a different PR, if you want the makefile related ones to be merged sooner.

2021-11-15 17:15 UTC, joaquimrocha commented on frontend/Makefile
> +run: install
You added this dependency which makes the run command very slow. I'd prefer to do it based on whether frontend/node_modules exist. This doesn't ensure we're running the latest install, but `make run` is a development command so we can expect a level of independence/responsibility for the developer.

2021-11-24 09:38 UTC, guilhem commented on frontend/Makefile
> +run: install
For buildah, a patch fixed it... but not yet released :( https://github.com/containers/buildah/pull/3574

For GitHub actions, that's why I added a special action that install buildkit.

2021-11-24 09:38 UTC, guilhem commented
For buildah, a patch fixed it... but not yet released :( https://github.com/containers/buildah/pull/3574

For GitHub actions, that's why I added a special action that install buildkit.

2021-11-24 15:00 UTC, joaquimrocha commented
@guilhem , I have tried again with an updated podman and I could build it.
However, with docker in my Fedora box I have permissions issues when mounting the cache. Not sure I am doing something wrong or whether it's docker's version (from the moby-engine 20.10.10).

I wonder if the docker related changes will become an issue for other users too. What do you think?

We can also always extract the docker related changes into a new PR and merge the rest, as the Makefile LGTM now.

2021-11-24 15:15 UTC, guilhem commented
> I wonder if the docker related changes will become an issue for other users too. What do you think?

I tried to do it the "actual way" (it was some kind of challenge too).
But yes, some people without latest buildkit can have problems.

> We can also always extract the docker related changes into a new PR and merge the rest, as the Makefile LGTM now.

It sound a really good idea to me :)

2021-11-25 10:09 UTC, joaquimrocha commented
> > We can also always extract the docker related changes into a new PR and merge the rest, as the Makefile LGTM now.
> 
> It sound a really good idea to me :)

Thanks @guilhem . Since it was not clear who should do this, do you want to extract the Docker commits into a new PR yourself?
If you don't have time, let me know.

2021-12-17 11:03 UTC, joaquimrocha commented
> > > We can also always extract the docker related changes into a new PR and merge the rest, as the Makefile LGTM now.
> > 
> > 
> > It sound a really good idea to me :)
> 
> Thanks @guilhem . Since it was not clear who should do this, do you want to extract the Docker commits into a new PR yourself? If you don't have time, let me know.

@guilhem , do you have time to split the docker changes out?

2021-12-17 14:48 UTC, guilhem commented
> > > > We can also always extract the docker related changes into a new PR and merge the rest, as the Makefile LGTM now.
> > > 
> > > 
> > > It sound a really good idea to me :)
> > 
> > 
> > Thanks @guilhem . Since it was not clear who should do this, do you want to extract the Docker commits into a new PR yourself? If you don't have time, let me know.
> 
> @guilhem , do you have time to split the docker changes out?

Working on it :)

2021-12-17 18:05 UTC, joaquimrocha approved these changes

2021-12-17 18:05 UTC, joaquimrocha commented
@guilhem Awesome! 🥳

2021-12-17 18:05 UTC, merged