backend: Add e2e test for OIDC auth mode
kinvolk/nebraska pull request #558
Opened 2022-01-21 11:32 UTC by yolossn

This patch adds end to end test for OIDC auth mode.

Signed-off-by: Santhosh Nagaraj S <santhosh@kinvolk.io>

2022-01-21 12:26 UTC, yolossn commented
I think the CI is failing because of golang version mismatch,Ill fix this. I have raised an issue for the same https://github.com/kinvolk/nebraska/pull/559.

2022-01-21 15:16 UTC, joaquimrocha approved these changes
Wow. This looks very comprehensive! Thanks for sticking to it, @yolossn !

2022-01-24 12:44 UTC, illume approved these changes
🎉 👍 wonderful, thanks :)

2022-01-24 15:55 UTC, illume commented on backend/test/auth/oidc/auth_test.go
> +	if os.Getenv("NEBRASKA_SKIP_TESTS") != "" {
Is NEBRASKA_SKIP_TESTS used for the login_test.go as well?

2022-01-24 15:56 UTC, illume commented
When I run tests locally with: `cd backend;make check-backend-with-container` I get a bunch of errors, including:
```
--- FAIL: TestLogin (3.99s)
    --- FAIL: TestLogin/invalid_login_redirect_url (0.34s)
        login_test.go:122: <nil>
        login_test.go:134:
                Error Trace:    login_test.go:134
                Error:          Received unexpected error:
                                Get "http://localhost:6000/login?login_redirect_url=http://localhost:9000": dial tcp 127.0.0.1:6000: connect: connection refused
                Test:           TestLogin/invalid_login_redirect_url
```

2022-01-24 15:58 UTC, illume requested changes
I was testing it locally and had a couple of issues mentioned in previous comments.

2022-01-25 11:02 UTC, yolossn commented on backend/test/auth/oidc/auth_test.go
> +	if os.Getenv("NEBRASKA_SKIP_TESTS") != "" {
This pattern is used across tests. It makes it easy to skip all the tests by setting the `NEBRASKA_SKIP_TESTS ` value, so I followed the same.

2022-01-25 11:03 UTC, yolossn commented
I am not able to reproduce it, by any chance is port 6000 used by some other application in your local machine?

2022-01-25 11:30 UTC, illume commented
No, there's nothing listening on 6000. I'll try and debug it.

2022-01-25 11:32 UTC, illume commented on backend/test/auth/oidc/auth_test.go
> +	if os.Getenv("NEBRASKA_SKIP_TESTS") != "" {
Yeah. Sorry I wasn't clear by putting the question here. 

Should it be used in "login_test.go" as well?

2022-01-25 23:31 UTC, illume commented on backend/test/auth/oidc/auth_test.go
> +	if os.Getenv("NEBRASKA_SKIP_TESTS") != "" {
Yeah, they should also do the skip. If you run `cd backend;make check` you'll see them fail if you don't have a db running.

2022-01-25 23:56 UTC, illume commented
Ok, quite a bit of messing about, and found a few things but not any fixes yet...

---

Seems we now have some sort of build issue with docker images not being rebuilt when things change. After pruning my containers and images I got things working in the last commit on proof-of-concept3 branch. I see this in the proof-of-concept3 branch, but haven't gone back to see when the issue was introduced yet.

However, even after pruning, I can't get this branch to pass tests (with `make check` or `make check-backend-with-container`). 

- Make check needs the skipping via env added.
- For testing with the container, seems a server is staying open after a test... which causes the next test to fail because the port is open(I think). Maybe a bit more error checking/logging and deferring the shutdown so it runs on a test failure would help here.

2022-01-27 07:53 UTC, yolossn commented
Oh got the reason for the docker images not building. I think we should add `--build` tag. I'll look into the the `make check` and the server not shutting down properly.

2022-01-31 10:41 UTC, joaquimrocha commented on backend/test/auth/oidc/login_test.go
> +			time.Sleep(100 * time.Millisecond)
This could be simplified by moving to line 87, before the continue.

2022-01-31 10:41 UTC, joaquimrocha commented on backend/test/auth/oidc/login_test.go
> +		req, err := http.NewRequest("GET", fmt.Sprintf("%s/health", testServerURL), nil)
I wonder if checking for the /config would achieve the same without adding a new endpoint. I still understand this endpoint is fairly innocent in any case.

2022-01-31 10:41 UTC, joaquimrocha commented on backend/test/auth/oidc/login_test.go
> +		// time.Sleep(100 * time.Millisecond)
This should be removed when adding te waitServerReady to the rest of the code.

2022-01-31 11:19 UTC, illume commented on backend/test/auth/oidc/login_test.go
> +			time.Sleep(100 * time.Millisecond)
The idea here is that it will only sleep if there is a failure to GET. So the first time through the loop there is no sleep. It should also sleep if there is any sort of error.

2022-01-31 11:42 UTC, illume commented on backend/test/auth/oidc/login_test.go
> +		req, err := http.NewRequest("GET", fmt.Sprintf("%s/health", testServerURL), nil)
Good idea. The only downsides I can see are it generates json and has a separate purpose.

2022-01-31 14:04 UTC, joaquimrocha commented on backend/test/auth/oidc/login_test.go
> +			time.Sleep(100 * time.Millisecond)
Isn't that what the suggestion I made would accomplish?

2022-01-31 14:09 UTC, illume commented on backend/test/auth/oidc/login_test.go
> +			time.Sleep(100 * time.Millisecond)
If it's inside the first error check if on line 87 then it would not sleep if the error happens after that in one of the other error check blocks.

2022-01-31 14:10 UTC, illume commented on backend/test/auth/oidc/login_test.go
> +		req, err := http.NewRequest("GET", fmt.Sprintf("%s/health", testServerURL), nil)
@yolossn if we keep /health we need to add it to the spec. Should I do this?

2022-01-31 14:18 UTC, joaquimrocha commented on backend/test/auth/oidc/login_test.go
> +			time.Sleep(100 * time.Millisecond)
Okay. The logic still looks like it could be simplified IMO, but it's not grave how it is.
Let's move on with it.

2022-01-31 14:23 UTC, joaquimrocha commented on backend/test/auth/oidc/login_test.go
> +		req, err := http.NewRequest("GET", fmt.Sprintf("%s/health", testServerURL), nil)
I'll let you folks decide.
IMO, health is just checking if the server is up but not a full reflection that the service is running as the name/concept may suggest. So I'd use /config for that purpose and not add the new endpoint (unless we make it more about health than about testing if the server responds).

2022-01-31 14:24 UTC, joaquimrocha commented
@yolossn , once the final touches are done, and since you've mentioned it now also works for you, I think the commits should be squashed together onto your original one and merged.

2022-01-31 15:29 UTC, merged