backend: Fix flatcar packages path bug
kinvolk/nebraska pull request #578
Opened 2022-02-23 14:32 UTC by yolossn

This patch fixes a bug that redirected the
flatcar packages request to the index.html
file.

Signed-off-by: Santhosh Nagaraj S <santhosh@kinvolk.io>

2022-02-23 16:19 UTC, jepio commented on backend/pkg/server/server.go
> +				if dir == "/flatcar/" {
Also this needs to be conditional on -host-flatcar-packages.

2022-02-23 16:20 UTC, yolossn commented on backend/pkg/server/server.go
> +				if dir == "/flatcar/" {
Hey @jepio, This is because these endpoints are dynamically created and we follow Open API documentation to generate handlers for the defined set of endpoints. So these dynamic endpoints are considered "Not found (404)" by default and that is why it is handled in the error handler.

2022-02-23 17:02 UTC, yolossn commented on backend/pkg/server/server.go
> +				if dir == "/flatcar/" {
>But the error handler only resolves the index.html in case of 404 file, other static assets are being served via e.Static(), or am I wrong? The flatcar packages are also static assets so it would seem cleaner to serve them the same way. Does open API not make a distinction between API endpoints and static assets?

There are dynamic endpoints in the frontend like "nebraska.com/application/:appId" etc in this case it is redirected to the `index.html`
> conf.FlatcarPackagesPath defaults to "", so it would serve arbitrary files from the working directory of nebraska right? That doesn't sound safe.

Aah, good catch. I thought anyways the file wont be available and 404 will be returned. Will add another level of check.

2022-02-24 10:26 UTC, joaquimrocha requested changes

2022-02-24 10:26 UTC, joaquimrocha commented on backend/pkg/server/server.go
> +					if dir == "/flatcar/" {
The 2 occurrences of `/flatcar/` should be used from a const, to avoid future problems.

2022-02-24 10:26 UTC, joaquimrocha commented on backend/test/api/flatcar_package_test.go
> +		go server.Start(serverPortStr)
Don't you have to check for whether the server is already up, otherwise we may have a race issue like before.

2022-02-24 13:43 UTC, illume commented on backend/pkg/server/server.go
> +				if dir == "/flatcar/" {
I think we need to consider the topic of dynamic endpoints and the schema in depth a bit. It would be good to represent dynamic endpoints in the schema somehow. I can't remember if we looked into this already for the other dynamic end points?

2022-02-24 15:42 UTC, teizz commented
Sorry to bump in like this. Reading the thread I didn't really find the answer to the question by @jepio why this couldn't be solved with a `e.Static`. Handling serving files from the error handler doesn't seem like the most elegant solution imho.

I'm not at all familiar with the code, or very experienced with Echo, but having added the following works for me:
```
diff --git a/backend/pkg/server/server.go b/backend/pkg/server/server.go
index 9b7c57b..81e1d9a 100644
--- a/backend/pkg/server/server.go
+++ b/backend/pkg/server/server.go
@@ -37,7 +37,7 @@ var (
        middlewareSkipper = func(c echo.Context) bool {
                requestPath := c.Path()
 
-               paths := []string{"/health", "/metrics", "/config", "/v1/update", "/*"}
+               paths := []string{"/health", "/metrics", "/config", "/v1/update", "/flatcar/*", "/*"}
                for _, path := range paths {
                        if requestPath == path {
                                return true
@@ -106,6 +106,9 @@ func New(conf *config.Config, db *db.API) (*echo.Echo, error) {
                return nil, fmt.Errorf("Error setting up handlers: %w", err)
        }
 
+       if conf.HostFlatcarPackages && conf.FlatcarPackagesPath != "" {
+               e.Static("/flatcar/", conf.FlatcarPackagesPath)
+       }
        e.Static("/", conf.HTTPStaticDir)
 
        e.HTTPErrorHandler = func(err error, c echo.Context) {
```

2022-02-24 16:56 UTC, yolossn commented
@teizz I didn't think of adding the `/flatcar/*` path to the skipper and the OpenAPI validation middleware was returning "Status 404" as it is not defined in the specification YAML. So I handled it using the `ErrorHandler` like we previously handled the dynamic endpoints from the frontend that had to be redirected to `index.html`. Sorry my bad, Thanks for pointing it out. I'll update the PR.

2022-02-25 09:35 UTC, joaquimrocha approved these changes

2022-02-25 09:36 UTC, joaquimrocha commented
LGTM, but maybe @illume wants to take an extra look before merging.

2022-02-25 11:05 UTC, illume commented
Hrmm. I can't get `make check-backend-with-container` working for me locally. Looking into it.

2022-02-25 11:32 UTC, illume commented
Added waitServerReady to the second test and it worked...

```golang
(flatcar-path-fix)$ git diff
diff --git a/backend/test/api/flatcar_package_test.go b/backend/test/api/flatcar_package_test.go
index bde48cb..3bd21bd 100644
--- a/backend/test/api/flatcar_package_test.go
+++ b/backend/test/api/flatcar_package_test.go
@@ -85,6 +85,9 @@ func TestHostFlatcarPackage(t *testing.T) {
                //nolint:errcheck
                defer server.Shutdown(context.Background())

+               _, err = waitServerReady(fmt.Sprintf("http://localhost:%d", serverPort))
+               require.NoError(t, err)
+
                resp, err := http.Get(fmt.Sprintf("http://localhost:%d/flatcar/%s", serverPort, fileName))
                assert.NoError(t, err)
                assert.NotNil(t, resp)
```

2022-02-25 11:34 UTC, illume commented on backend/test/api/flatcar_package_test.go
> +		HostFlatcarPackages: true,
I don't know if it's important to define what `HostFlatcarPackages: false` does?

2022-02-25 11:38 UTC, illume approved these changes
Thanks for fixing this, and for adding the tests! 👍 🎉 

(Looks good to me when the wait patch is applied)

2022-02-25 12:24 UTC, yolossn commented on backend/test/api/flatcar_package_test.go
> +		HostFlatcarPackages: true,
Do you mean add test cases for `HostFlatcarPackages: false`?

2022-02-25 13:13 UTC, illume commented on backend/test/api/flatcar_package_test.go
> +		HostFlatcarPackages: true,
I personally don't think it matters...

2022-02-25 13:17 UTC, merged