backend: Fix Version Breakdown graph
kinvolk/nebraska pull request #593
Opened 2022-04-06 05:53 UTC by yolossn

This patch breaks the version breakdown query
into multiple sub queries and runs them in
parallel using go routines for better
performance.

Signed-off-by: Santhosh Nagaraj S <santhosh@kinvolk.io>

2022-04-07 17:37 UTC, yolossn commented
The query is broken into 3 different parts and then the final output is computed, and the queries are run in parallel for performance.
- Instances without any instance status history (ie instances that have not been updated), In this case, the latest version in instance_application table is used.
- Instances that have updated in the timespan (30 days/7days etc), then fetch the instance status histories and compute the timeline.
- Instances that have been updated but not in the timespan. In this case, consider the latest instance status history version for all the spans in the timespan.

2022-04-07 17:37 UTC, yolossn commented
ToDo:

- [ ] Check if new indexes can be added 
- [ ]  Remove the indexes that were introduced for the old query.

2022-04-12 05:38 UTC, yolossn commented
The response time for 280000 instances.
![image](https://user-images.githubusercontent.com/22731013/162887991-a0602d07-d93e-486c-ab4d-1d575721293a.png)

2022-04-20 15:57 UTC, joaquimrocha reviewed
Thanks for all this work. I know things were already very difficult to understand before, but it was one query. Now it's several steps, so I'd like to ask for a bit more detailed comments in each one, so next time we have to touch it, we can understand it quicker.

2022-04-20 15:57 UTC, joaquimrocha commented on backend/pkg/api/groups.go
> +		with time_series as ( select * from generate_series( now() - interval '%[2]s', now(), interval '%[3]s' ) as ts ), instances as ( select ia.instance_id, case when last_update_granted_ts is not null
Can we break this line for better readability?

2022-04-20 15:57 UTC, joaquimrocha commented on backend/pkg/api/groups.go
> +			_, ok := timelineCount[span][vc.Version]
Nit: I'd get the result here, and if "not ok", I'd set up the result as 0. So below you'd have only to assign the value to the result + unit64(vc.Count) once.

2022-04-29 17:01 UTC, joaquimrocha requested changes
I think you meant to add the comment to the previous commit, not the indexes one, right?
The comments, LGTM, so after this tidy up, it should be good to merge.

2022-05-04 20:20 UTC, joaquimrocha approved these changes

2022-05-04 20:20 UTC, merged

2022-05-04 20:20 UTC, joaquimrocha commented
Awesome. Thanks.