backend: Add migration down support
kinvolk/nebraska pull request #604
Opened 2022-05-02 06:55 UTC by yolossn

2022-05-02 06:59 UTC, yolossn commented
The `migrate-down` command should be used to remove the last migrations before reverting to an old version of Nebraska. One question still remains, how will the admin know how many migrations should be reverted ? Should we start adding the migrations introduced along with the releases going on ? @joaquimrocha  thoughts ?

2022-05-02 09:32 UTC, joaquimrocha commented
> The `migrate-down` command should be used to remove the last migrations before reverting to an old version of Nebraska. One question still remains, how will the admin know how many migrations should be reverted ? Should we start adding the migrations introduced along with the releases going on ? @joaquimrocha thoughts ?

I think maybe we can an argument support to migrate-down, so users can do: `--migrate-down=004` (exclusive, i.e. down to 004 which will be the last migration applied applied).

Users can use git to get the last migration for a past version:
`git show 2.4.0:./backend/pkg/api/db/migrations | tail -n1`

Alternatively we could add a command called `db-migrate` with the following options:
`nebraska db-migrate --down-to=004`: this migrations down till a migration starting with 004 (this one is not migrated down, i.e. it's exclusive)
`nebraska db-migrate --show`: this lists the current migrations for the current version.

(but this command would only be available in new versions, so maybe it's not so useful when users have git)

WDYT?

2022-05-13 12:45 UTC, yolossn commented
Makes sense to use the migration id to migrate down, I think we should add documentation for the same.

2022-05-13 12:56 UTC, yolossn commented
Makes sense to use the migration id for migrate down, I will add the documentation for the same.

2022-05-20 12:15 UTC, yolossn commented
Added docs for migrating to an older version of Nebraska.

2022-05-24 09:38 UTC, illume commented
> Added test 👍🏽

Awesome. Thanks!

2022-05-24 13:43 UTC, joaquimrocha requested changes
Found an issue in the docs.
BTW, `--migrate-down-to` sounds a bit complicated and is unrelated to DBs. Should we rename it as `--migrate-db-to` and support migrating up as well? (maybe in the beginning we can just support migrating down, but it's important that the command name makes sense)

2022-05-24 13:43 UTC, joaquimrocha commented on docs/migrate-to-older-version.md
> +For example to find the migrations that were introduced as part of `2.4.0` release clone the Nebraska repo and run.
I think this article is a bit confusing. The command associated with this phrase doesn't necessarily show the newly added files in this folder for this tag, it just lists the contents of that dir, for that tag (so it is the same result for 2.4.1).

It should instead say that if users want to migrate to a version, like 2.4.0, they should run the command you wrote (gets them the last migration considered in 2.4.0) and run the `--migrate-down-to 0013`.

2022-05-25 14:11 UTC, joaquimrocha requested changes
Left a comment about the command's name. Also, I don't think the docs were updated.

2022-05-25 14:11 UTC, joaquimrocha commented on backend/pkg/config/config.go
> +	f.String("rollback-db-to", "", "Rollback db migration to the provided id, eg:0003")
As I tried to explain before, I think we can use this command later for migrating up too. So we should not go with a name that hints migrating down, which both this + the previous version do.
I think something like `migrate-db-to 0013` is more adequate but could also be `set-db-migration 0013`.

BTW, if you touch this line, please also make `db` -> `DB`.

2022-05-30 13:19 UTC, joaquimrocha approved these changes

2022-05-30 13:19 UTC, merged