Support Podman in docker-compose setup
kinvolk/nebraska pull request #628
Opened 2022-11-24 19:41 UTC by pothos

The "docker compose" subcommand to run docker-compose does not work when "docker" is a symlink to "podman" and "docker-compose" is a symlink to "podman-compose".
Use "docker-compose" instead of the subcommand to support running with Podman and give a hint in the docs on podman-compose.

## How to use

With the mentioned symlinks.

## Testing done

Tested `make test-service-up`

2022-11-24 22:48 UTC, illume requested changes
👍thanks

As well as supporting podman...  I like that removing the compose plugin step as is done here makes it easier for people. I think `docker compose` hasn't really caught on, and docker-compose is still a bit more widespread in scripts.

IMHO the docs should now change to link to the docker-compose standalone docs rather than the sub command plugin docs https://docs.docker.com/compose/install/other/

2022-11-24 22:48 UTC, illume commented on docs/development.md
> +If so, see https://docs.docker.com/compose/cli-command/#install-on-linux or https://github.com/containers/podman-compose (with a symlink)
I think we should then link to the docker-compose standalone install page. https://docs.docker.com/compose/install/other/

2022-11-25 12:11 UTC, t-lo commented
For podman-compose compatibility please also take this into account: https://github.com/kinvolk/nebraska/pull/627/files#diff-91315b4cf15177fd76e06ff8c63ccad1721d8ec2d518a82252aef2bda6b95f49R38-R39

2022-11-25 13:30 UTC, pothos commented on docs/development.md
> +If so, see https://docs.docker.com/compose/cli-command/#install-on-linux or https://github.com/containers/podman-compose (with a symlink)
Ok, done

2022-11-25 14:02 UTC, yolossn approved these changes
LGTM

2022-11-25 16:50 UTC, merged