vbatts/backend update
kinvolk/nebraska pull request #643
Opened 2023-03-10 17:07 UTC by vbatts

# linters and golang updates

fix inconsistencies in reported linting, and differences in the versions of golang used.

## Testing done

`make`
 and now the github actions output

2023-03-10 19:21 UTC, vbatts commented
ok. Ready for review.

2023-03-19 18:08 UTC, yolossn requested changes

2023-03-19 18:08 UTC, yolossn commented on .github/workflows/backend.yml
> +        make all ci
The `all` recipe is for building and running both `frontend` and `backend`. Just `make ci` should do here.

2023-03-20 14:16 UTC, vbatts commented on .github/workflows/backend.yml
> +        make all ci
ah, this should `cd backend` to run the backend test. The reason I added this at all, is that I was seeing failures locally, that were not getting caught in the github action.

2023-03-20 14:18 UTC, vbatts commented on .github/workflows/backend.yml
> +        make all ci
oh, it is already in the backend directory: `working-directory: backend`
This is not running the frontend build.

2023-03-20 14:19 UTC, yolossn commented on .github/workflows/backend.yml
> +        make all ci
We have a separate action for the frontend.

2023-03-20 14:20 UTC, vbatts commented on .github/workflows/backend.yml
> +        make all ci
correct. This is not running any of the frontend make targets. It's running `make all ci` from within the `./backend/` directory

2023-03-20 15:08 UTC, merged